### ISSUE TITLE
Social Fields are not used on any page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#10]
System takes the social fields of the contact, but they are not being displayed/used anywhere on the contact page.

**Comment by mitulpanch** [comment]
It's on icon left side I think

**Comment by risipatel** [comment]
Not able to find those icons.
![screenshot from 2019-01-21 17-47-32](https://user-images.githubusercontent.com/46882833/51474292-cba5e600-1da4-11e9-8239-91c333a6b450.png)

**Comment by mitulpanch** [comment]
Ok

**Comment by risipatel** [comment]
Google+ icon is not there. @mitulpanch

**Comment by mitulpanch** [comment]
Its there on Contact View Page

**Comment by mitulpanch** [comment]
![annotation 2019-02-27 184748](https://user-images.githubusercontent.com/5259926/53492984-34793000-3ac0-11e9-96ea-90afee5e25f1.jpg)

**Comment by mitulpanch** [comment]
Removing Google+. as its service is shutting down
