### ISSUE TITLE
When we click on help button in Api Calls it redirects to wrong URL & showing 404 msg

### ISSUE THREAD

**Issue by Avinash-ecb** [EasyCloudConsultants/EasyCloudBooks#108]
**To Reproduce**
1. Go to Api Calls page
2. Click on 'help button'
3. It redirects to wrong URL

**Actual behavior for api calls page**
When we click help button in api calls it redirects to this url https://help.easycloudbooks.com/User/apicall?ir=1 and display 404 error message

**Screenshots**

![screenshot_2019-02-17 easycloudbooks](https://user-images.githubusercontent.com/46588125/52909451-952d8f00-32ae-11e9-9e48-b2267e0affa0.png)

**Comment by mitulpanch** [comment]
@dharmendraecb Add this Page Dharmendra

**Comment by mitulpanch** [comment]
#120 Generated for Further Reporting
@ajayrajecb  @Avinash-ecb
