### ISSUE TITLE
Query builder page parameter help link issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#112]
1. edit any query in query builder page, click on button shown in image
![2019-02-18_12-40-43](https://user-images.githubusercontent.com/46882964/52937623-a5fd0400-3385-11e9-9a62-416cf622ad8f.png)
2. desired page open with no results
![2019-02-18_12-53-39](https://user-images.githubusercontent.com/46882964/52937648-bdd48800-3385-11e9-8951-3059ae9345c8.png)

**Comment by mitulpanch** [comment]
No Issue for EasyCloudBooks
Help Section assigned to @dharmendraecb

**Comment by dharmendraecb** [comment]
Issue is solved @ajayrajecb
