### ISSUE TITLE
Question regarding Query Builder 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#113]
1. what is the use of Reset for Contact, Company and Create mail.

2. reset and restart button works similar.

![2019-02-18_14-19-25](https://user-images.githubusercontent.com/46882964/52939473-46552780-338a-11e9-97f5-fadcc9743b85.png)

**Comment by mitulpanch** [comment]
not used anymore
need to reset on later stages
