### ISSUE TITLE
Voucher roles is not working.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#118]
**Describe the bug**
Allows to create voucher even if user doesn't have a role of that voucher.

**To Reproduce**
1. Go to 'Accounts Page'.
2. Click on 'Voucher Roles'
3. Untick yourself from any voucher type.
4. Now try to create that voucher.

**Expected behavior**
Shouldn't allow to create voucher, if user doesn't have role of that voucher.

**Comment by mitulpanch** [comment]
have changed many things, it should work now
if still problem please pin issue

**Comment by risipatel** [comment]
Still voucher role functionality is not working. @mitulpanch
