### ISSUE TITLE
DrpDwn of custom filter gets stucked on Accounts page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#119]
**To Reproduce**
1. Go to 'Accounts Page'
2. Click on '+' btn of custom filter.
3. Click on drpdwn of custom filter.
4. Click on 'x' clear btn of Past query/New Name.

**Screenshots**
![screenshot from 2019-02-19 17-50-03](https://user-images.githubusercontent.com/46882833/53014740-5abf2000-346f-11e9-8a11-40438c2052d6.png)

**Comment by mitulpanch** [comment]
Not able to reproduce

**Comment by ajayrajecb** [comment]
> 
> 
> Not able to reproduce

Open Custom filter and leave it till token refresh, or 2, 3 minutes, parameter dropdown popup stuck,

**Comment by mitulpanch** [comment]
attempted to solve. Please check
