### ISSUE TITLE
In Accounts, create Journel type voucher issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#126]
1.Goto Accounts page.
2. Create Voucher Journal type select from drop down.
3. debit and credit dropdown not showing SL, UL, accounts. 
4. After sundry debtors dropdown blank.

![2019-02-20_14-26-37](https://user-images.githubusercontent.com/46882964/53079036-97e0ec00-351b-11e9-9bc3-fd6cd11f03ec.png)

**Comment by mitulpanch** [comment]
Filter account it wont happen.

Plugin seems to have limitation on max  accounts in list
but when searching it is not making any error. 

I guess this is not a problem. nobody will scroll that much
