### ISSUE TITLE
Time sheet not working

### ISSUE THREAD

**Issue by dharmendraecb** [EasyCloudConsultants/EasyCloudBooks#129]
**To Reproduce**
1. Go to 'Time Sheet page '
2. Start  'Timer'
3. After wait 10 minutes.
4. Refresh Browser tab.
5. See Error

**Actual behavior**

- when timer is start and after waiting 10 minutes if we refresh browser tab timer is stop.
- time Sheet not Count Time.
- if user login and start timer and logout and again login and timer already start.

**Comment by mitulpanch** [comment]
Upload Image with  Error

**Comment by dharmendraecb** [comment]
- when timer is start and after waiting 5 minutes if we refresh browser tab timer is stop Automatic.
- Time Sheet not Count Time.

![inked53087271-b69bae80-352c-11e9-91c8-590a133e86c4_li 2](https://user-images.githubusercontent.com/46588108/53087409-198d4580-352d-11e9-9647-bdc75983e448.jpg)
