### ISSUE TITLE
Should have some limitation for displaying Phone numbers in non-expanded view of contact.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#13]
System displays all the contact numbers in non-expanded view of contact, And that disturbs the designing of page.
![screenshot from 2019-01-21 18-26-19](https://user-images.githubusercontent.com/46882833/51475980-12e2a580-1daa-11e9-8e46-b9ee9299b5e6.png)

**Comment by mitulpanch** [comment]
Now Limited to 2

**Comment by mitulpanch** [comment]
Please Provide your Views @vinpahilwani
