### ISSUE TITLE
Service can not add in team in team page

### ISSUE THREAD

**Issue by Avinash-ecb** [EasyCloudConsultants/EasyCloudBooks#130]
**To Reproduce**
1. Go to 'Team page'
2. Add Team and click on save button
3. now click on arrow and expand row
4. now try to add service drop down never respond
5. See error

**Actual behavior**
when try to add service in team it can't add service in team

**Screenshots**
![screenshot_2019-02-20 easycloudbooks - the smart way of managing practice 1](https://user-images.githubusercontent.com/46588125/53087712-cb2c7680-352d-11e9-9177-e45d9c4f498c.png)

**Comment by mitulpanch** [comment]
Not able to Reproduce
