### ISSUE TITLE
In Documents Page, Download recently uploaded images give error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#133]
1. upload image in any company.
2. right click on it and click download gives below error

![2019-02-21_14-08-28](https://user-images.githubusercontent.com/46882964/53155132-6bdc6e00-35e2-11e9-8163-ec936ac0ab08.png)

**Comment by ajayrajecb** [comment]
Documents Open, Download is not working, gives token invalid error.

**Comment by mitulpanch** [comment]
possible solve
