### ISSUE TITLE
In documents, email, sms feature is not working

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#134]
1. file uploads in company
2. right click on it, try to mail and sms it .
3. not able to send email, and send sms - token update .
![2019-02-21_15-40-27](https://user-images.githubusercontent.com/46882964/53161729-903f4700-35f0-11e9-874d-740e0cbfeea7.png)

**Comment by mitulpanch** [comment]
Email will start after all company database upload
