### ISSUE TITLE
In Add tax + button URL issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#138]
#136  
**To Reproduce**
1. Go to 'Accounts Page'
2. Click on '+Account' btn.
3. Select 'Direct Income' in Account Type field.
4. Click on Add Tax button, 
5. Click on + button throws to wrong URL, see below image

![2019-02-25_14-14-30](https://user-images.githubusercontent.com/46882964/53325065-68a9f080-3908-11e9-8965-bbc2bb1d74bd.png)

![2019-02-25_14-20-16](https://user-images.githubusercontent.com/46882964/53325114-85462880-3908-11e9-89b0-d96d8a684656.png)

**Comment by risipatel** [comment]
Same Issue on AccountsDetailPage,
1. Go to Accounts Page.
2. Click on View btn of Sales Account.
3. Click on Edit Btn.
4. Click on Add Tax Btn.
5. Click on '+' btn of tax settings field.

![screenshot from 2019-02-25 18-10-40](https://user-images.githubusercontent.com/46882833/53338153-01e8ff00-3929-11e9-8753-73b16f15ad4d.png)
