### ISSUE TITLE
On Contact Badge Project URL Bug

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#14]
Steps to reproduce:-
1. Open contact page.
2. Mouse Over on any contact
3. Click on go to Projects Icon
4. Project page open with filter view
5. Click on clear filter button.
6. Error page appear "
![cpb](https://user-images.githubusercontent.com/46882964/51514865-8ed6ff00-1e37-11e9-8792-dfcaf1f4f9bc.png)

**Comment by mitulpanch** [comment]
Error is on Project Page
Solvedin 5.0.6965.30948
