### ISSUE TITLE
Allows to add same tax settings multiple times.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#144]
**To Reproduce**
1. Go to 'Accounts Page'
2. Click on 'View btn' of Sales Account.
3. Click on edit btn.
4. Add same Tax twice.

**Screenshots**
![screenshot from 2019-03-05 13-03-53](https://user-images.githubusercontent.com/46882833/53788231-2fe0cb80-3f47-11e9-8769-faf93f2726e6.png)

**Comment by vinpahilwani** [comment]
We are going to introduce new functionality for this. So, leave this for now.
