### ISSUE TITLE
Allows to delete linked project without any warning message.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#146]
**Describe the bug**
Should display some warning message while trying to delete linked projects.

**Comment by vinpahilwani** [comment]
Linked project means? linked to time sheet or billing?? i guess when project is finished it can not be deleted. Kindly check that can we delete project.

**Comment by risipatel** [comment]
As discussed with Vinod Sir, kindly display warning message.

**Comment by mitulpanch** [comment]
I actually don't know that, whether user is adding/editing or removing project(s).
as multiple project added or removed its bit difficult to find out.

still we can do this we little longer time in development for a message.
I suggest for a message this much work is not required.

still required? @vinpahilwani

**Comment by vinpahilwani** [comment]
dont do anything. as far as timesheet on deleted projects is concerned we need to cover itup in summary report.
