### ISSUE TITLE
Need to correct url of project btn on detailspage of Contact and Company.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#15]
Redirects to wrong url on click of project btn on detailspage of contact and company.
Wrong URL: https://user.devecbs.xyz/**project**?crid=92033&acid=1
Correct URL: https://user.devecbs.xyz/**projects**?crid=92033&acid=1

![screenshot from 2019-01-22 12-12-03](https://user-images.githubusercontent.com/46882833/51516898-f5135000-1e3e-11e9-8112-41766cb4e8e2.png)

**Comment by risipatel** [comment]
For company page it is working properly.

**Comment by risipatel** [comment]
But for contact's details page, it redirects user to 

> user.devecbs.xyz/projects?**uid**=19&acid=1

 instead of 

> user.devecbs.xyz/projects?**coid**=19&acid=1.

**Comment by mitulpanch** [comment]
in 5.0.20190131

**Comment by ajayrajecb** [comment]
> 
> 
> in 5.0.20190131

its solved but it should be open in new tab. currently this opened in same window, please solve it on open in new tab

**Comment by ajayrajecb** [comment]
its solved but in **contact page** it should be open in new tab. currently this opened in same window, please solve it on open in new tab
