### ISSUE TITLE
Few details are missing on print view of ledger.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#151]
**To Reproduce**
1. Go to Accounts Page
2. Click on View btn of any account.
3. Click on Print btn.

**Screenshots**
On Live
![Screenshot from 2019-03-13 16-28-54](https://user-images.githubusercontent.com/46882833/54274901-4aeab580-45af-11e9-91f7-ff74721b244d.png)

On ECBS
![Screenshot from 2019-03-13 16-27-00](https://user-images.githubusercontent.com/46882833/54274877-46260180-45af-11e9-907f-d526910b9c0b.png)

**Comment by mitulpanch** [comment]
Query Builder is no longer supported
@vinpahilwani @sureshsirvi

**Comment by mitulpanch** [comment]
Anything Else missing? @risipatel

**Comment by risipatel** [comment]
Date, Type, Debit, Credit, Running Balance and Current Balance are the fields that is missing on Ledger Preview.

**Comment by mitulpanch** [comment]
It varies on type and what type of items coming. 
Then also I will check it

**Comment by mitulpanch** [comment]
Is this still applicable?
