### ISSUE TITLE
Arrow of Debit and Credit drpdwn points in wrong direction

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#152]
**Describe the bug**
when user add 3rd account in Debit or Credit side then direction of the arrow points in opposite direction.

**To Reproduce**
1. Go to 'Accounts Page'
2. Click on '+ Voucher'
3. Add 2 New lines in the debit side.
4. Now add 3rd and 4th line and check the arrow.

**Screenshots**
![Screenshot from 2019-03-13 18-11-36](https://user-images.githubusercontent.com/46882833/54280069-93f53680-45bc-11e9-914a-37cc4bb3d8ed.png)

**Comment by mitulpanch** [comment]
This is not Error. Plug in shows it, on click overlay will open in arrow direction
