### ISSUE TITLE
Documents Page file upload error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#153]
**To Reproduce**
1. Go to Documents Page
2. Open any company for exp Ajayraj
3. Create new folder name test, and drag and drop image file in it.

![2019-03-14_14-06-52](https://user-images.githubusercontent.com/46882964/54342685-218b6180-4663-11e9-9970-93ad85e23b0b.png)

4. try to upload files by browse files gives this error
![2019-03-14_14-07-55](https://user-images.githubusercontent.com/46882964/54342724-3d8f0300-4663-11e9-9139-596e30f60f14.png)

**Comment by mitulpanch** [comment]
possible solve

**Comment by ajayrajecb** [comment]
![2019-03-23_10-40-05](https://user-images.githubusercontent.com/46882964/54861911-0f42af00-4d58-11e9-957f-155ffb9c8861.png)

![2019-03-23_10-41-00](https://user-images.githubusercontent.com/46882964/54861918-326d5e80-4d58-11e9-8da5-8dc979766b2a.png)
