### ISSUE TITLE
Adding new subtype resets Debit and credit fields.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#157]
**To Reproduce**
1. Go to 'Accounts Page'
2. Click on '+Voucher'
3. Add 2 lines credit and debit side.
4. Add new Sub type.

**Actual Result**
Resets debit and credit fields.

**Expected behavior**
Should affect debit and credit fields.

**Comment by mitulpanch** [comment]
It's reset by default, as it is required  in new entry or reset entry
