### ISSUE TITLE
Project Page 'Show Documents' Button role issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#158]
1. I don't have Documents page access role but when we go to project page and open any project, 
Show Documents Button available there.

![2019-03-15_10-35-09](https://user-images.githubusercontent.com/46882964/54409933-46d5a980-470f-11e9-9965-038102c5a968.png)

**Comment by ajayrajecb** [comment]
![2019-03-23_10-34-57](https://user-images.githubusercontent.com/46882964/54861860-68f6a980-4d57-11e9-97eb-f818266c2ee8.png)

![2019-03-23_10-35-22](https://user-images.githubusercontent.com/46882964/54861865-6f852100-4d57-11e9-98df-f1f31886e0d0.png)

**Comment by mitulpanch** [comment]
if you are in project you can see document.
this is base requirement
