### ISSUE TITLE
Document Log page, deleted files recovery gives error.

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#159]
![2019-03-15_12-47-22](https://user-images.githubusercontent.com/46882964/54414981-f2d3c080-4720-11e9-919d-4da17aa5adf1.png)

Deleted files show in log page but can't recover, error message appeared.

**Comment by mitulpanch** [comment]
This will only work on live

**Comment by ajayrajecb** [comment]
@ajayrajecb check it on live after release

**Comment by mitulpanch** [comment]
@ajayrajecb check this , if ok then please close

**Comment by ajayrajecb** [comment]
Documents Log is not working in sir company
