### ISSUE TITLE
Create New account btn on Tax settings page redirects user to wrong URL.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#160]
**To Reproduce**
1. Go to 'Tax Settings page'.
2. Click on '+Add Tax'.
3. Click on '+' btn.

**Screenshots**
![Screenshot from 2019-03-15 13-00-17](https://user-images.githubusercontent.com/46882833/54419779-4a2c5d80-472e-11e9-8559-cf8d57face8e.png)

**Comment by risipatel** [comment]
On hover of + btn, should display "Add/Edit Account" instead of "Add/Edit Tax".

**Comment by risipatel** [comment]
On hover of + btn, should display "Add/Edit Account" instead of "Add/Edit Tax".

**Comment by mitulpanch** [comment]
Title hover changed
