### ISSUE TITLE
Allows to create tax settings with more than 100% tax.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#161]
**Screenshots**
![Screenshot from 2019-03-15 16-08-27](https://user-images.githubusercontent.com/46882833/54426278-6daad480-473d-11e9-8eb5-9d67975d0bab.png)

**Comment by vinpahilwani** [comment]
Should keep limit of 1000%.

**Comment by mitulpanch** [comment]
Lesser than 1000 now

**Comment by risipatel** [comment]
Allows to enter more than 1000. So, validation message should be displayed. @mitulpanch

**Comment by risipatel** [comment]
Allows to type more than 1000, but on click of save btn server throws validation message.
![Screenshot from 2019-04-16 17-03-16](https://user-images.githubusercontent.com/46882833/56206274-9b02df00-6069-11e9-9ec7-0a393587b8a8.png)
