### ISSUE TITLE
On project Expansion Information

### ISSUE THREAD

**Issue by vinpahilwani** [EasyCloudConsultants/EasyCloudBooks#164]
**Describe the bug**
When i expand a particular project, it should display me information. it displays "not enough privilege"

**Comment by ajayrajecb** [comment]
This error occurs in  "Test Company" error

![2019-03-18_12-00-40](https://user-images.githubusercontent.com/46882964/54511065-b5b43c00-4975-11e9-804a-762b1062d19a.png)
