### ISSUE TITLE
In 'Test Company', Documents Page gives Package error (By Sumit)

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#166]
1. goto documents Page. 
2. type any company name.
3. gives package expire message

![2019-03-18_12-20-53](https://user-images.githubusercontent.com/46882964/54512580-b56a6f80-497a-11e9-9506-c1c66828eecb.png)

![2019-03-18_12-21-15](https://user-images.githubusercontent.com/46882964/54512587-ba2f2380-497a-11e9-92e1-eb9dc9d0dbe0.png)

**Comment by mitulpanch** [comment]
Not able to ReProduce
