### ISSUE TITLE
In 'Test Company', Settings Menu appear horizontal

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#168]
On live Settings menu alignment is vertical left, In 'Test Company' its appear horizontal top.

![2019-03-18_14-19-24](https://user-images.githubusercontent.com/46882964/54518779-23b72e00-498b-11e9-8be4-0120b3397e8c.png)

**Comment by mitulpanch** [comment]
yes it is changed now
