### ISSUE TITLE
In 'Test Company', Project view is not working (By Ashok Sir)

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#169]
Goto Project Page, click on view button, 
Red error popup message appeared.

![2019-03-18_14-42-57](https://user-images.githubusercontent.com/46882964/54519628-fa979d00-498c-11e9-8753-2864380e08a8.png)

**Comment by ajayrajecb** [comment]
Same error occurs in  Review Projects, Finished Projects page.

**Comment by mitulpanch** [comment]
Solved
