### ISSUE TITLE
Dashboard Team member status shown error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#173]
Goto dashboard, Team member status section is blank,
when any user start time tracker, user appear in this section otherwise no user shown here

![2019-03-18_15-31-21](https://user-images.githubusercontent.com/46882964/54522954-6a5d5600-4994-11e9-9a7a-dd3993a53fee.png)

**Comment by mitulpanch** [comment]
Not Possible as of now.
Working on It

**Comment by mitulpanch** [comment]
it takes 5 min to come to status bar

**Comment by ajayrajecb** [comment]
> 
> 
> it takes 5 min to come to status bar

if staff don't run time tracker , are they appear in status box ?
now not appear without time tracker play
