### ISSUE TITLE
2 differents companies open in 2 tabs. same time tracker running 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#175]
1. in tab 1 open Test company, time tracker runing.

![2019-03-18_16-01-38](https://user-images.githubusercontent.com/46882964/54525126-8283a400-4999-11e9-9a3d-d0683e735718.png)

2. in parallel tab open easycloudConsultants, same time tracker running in this company also.

![2019-03-18_16-03-45](https://user-images.githubusercontent.com/46882964/54525152-90d1c000-4999-11e9-9e7f-37af029cccd9.png)

**Comment by mitulpanch** [comment]
It is possible as of now
