### ISSUE TITLE
Vertical Scroll gets disabled when clicking on "+Add Action".

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#177]
**To Reproduce**
1. Go to 'Automation Page'
2. Click on 'Add Action' btn.
3. Click on close btn.

**Comment by mitulpanch** [comment]
Not able to reproduce

**Comment by risipatel** [comment]
Drpdwn is too small, cant even select last option i.e create bill.
![Screenshot from 2019-04-04 14-58-10](https://user-images.githubusercontent.com/46882833/55545328-9eea4500-56ea-11e9-80c4-bf70e52786b6.png)
