### ISSUE TITLE
In Documents, duplicate blank folders found Named Reports, Recovered 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#182]
In Common Folder, 2 Reports folder available, one is blank means no files in these folder.
2 Recovered folders are also available 

![2019-03-19_10-29-13](https://user-images.githubusercontent.com/46882964/54581412-ad6e0680-4a32-11e9-9a37-c369cbd9a1ee.png)

**Comment by mitulpanch** [comment]
Its solved i guess, not able to reproduce

**Comment by ajayrajecb** [comment]
2 reports folder shown there

![2019-03-23_10-06-46](https://user-images.githubusercontent.com/46882964/54861700-8f1a4a80-4d53-11e9-983e-c2c0a93c23ad.png)

**Comment by ajayrajecb** [comment]
> 
> 
> Its solved i guess, not able to reproduce

Not solved sir
