### ISSUE TITLE
Create new custom field button on contact page url is wrong

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#19]
Steps to reproduce error-
1. goto contact page.
2. click on view btn of any contact.
3. click on custom field btn.
4. click on + btn for add new custom field. pop appear.
5. in popup click on + btn for add/edit custom field.
6. custom field page opens with wrong url.(aspx)
![cfaddurl](https://user-images.githubusercontent.com/46882964/51596044-15660c00-1f1e-11e9-8b15-4ea2463eedf6.png)

**Comment by ajayrajecb** [comment]
not fixed, throws to customfilter.aspx page which is not available

**Comment by mitulpanch** [comment]
5.0.20190131
