### ISSUE TITLE
Newly created schedulers are being added at the bottom of list.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#190]
Instead of adding new schedulers at the top of the list, system adds it at end of the list.

**Comment by mitulpanch** [comment]
they have ddefault sorting as due date upcoming

**Comment by risipatel** [comment]
Due date wise bhi nh hai..
![Screenshot from 2019-03-28 17-19-48](https://user-images.githubusercontent.com/46882833/55155578-c2a70b80-517d-11e9-9f71-9186d0036439.png)
