### ISSUE TITLE
Doesn't allows user to Add Note on Account.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#194]
![Screenshot from 2019-03-22 11-21-27](https://user-images.githubusercontent.com/46882833/54803228-a6463300-4c94-11e9-9911-61ba39c78a3a.png)

**Comment by risipatel** [comment]
I have logged in ecbs using Afsin's credentials, then system allowed me to add note because Afsin was in the statement team.
So, System should allow me to add note, because I had all the roles.

**Comment by mitulpanch** [comment]
advance he?

**Comment by mitulpanch** [comment]
Live par pan aaj problem che?

**Comment by risipatel** [comment]
Advance role bandh hai toh mein jis account me hu usme add note ka option hi nh aa rha...
![Screenshot from 2019-03-27 16-45-15](https://user-images.githubusercontent.com/46882833/55077074-eb1b0100-50bc-11e9-96b3-e588e65492f4.png)

**Comment by ajayrajecb** [comment]
#241 by sirvi sir
