### ISSUE TITLE
Login - redirect from infosite to user site

### ISSUE THREAD

**Issue by vinpahilwani** [EasyCloudConsultants/EasyCloudBooks#195]
after login on infosite redirect to user site

**Comment by vinpahilwani** [comment]
Choose an company ki jagah select  any company to continue

**Comment by risipatel** [comment]
Login with auth code keeps user to infosite.

**Comment by risipatel** [comment]
https://www.easycloudbooks.com/logout?lasturl=&fromurl=https%3A%2F%2Fuser.easycloudbooks.com%2Flogoutall%3Freturnurl%3Dhttps%253A%252F%252Fwww.easycloudbooks.com%252Flogout%253Flasturl%253D

![image](https://user-images.githubusercontent.com/46882833/61632551-c3265d80-acaa-11e9-99ff-1300aa8e3528.png)

**Comment by risipatel** [comment]
1. Login to ECB
2. Log out from ECB
3. Will bring you here https://www.easycloudbooks.com/logout?lasturl=&fromurl=https%3A%2F%2Fuser.easycloudbooks.com%2Flogoutall%3Freturnurl%3Dhttps%253A%252F%252Fwww.easycloudbooks.com%252Flogout%253Flasturl%253D
