### ISSUE TITLE
Project "Created by" field is being displayed blank.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#20]

**Comment by risipatel** [comment]
Still being displayed on the projects page.
![screenshot from 2019-01-29 15-08-44](https://user-images.githubusercontent.com/46882833/51898849-d3ced880-23d7-11e9-98d7-034bd1e011e2.png)

**Comment by mitulpanch** [comment]
Removed. No Longer Required
