### ISSUE TITLE
After Export, file cant downloaded or open csv file

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#201]
After Export, file cant downloaded or open csv file

![2019-03-23_11-13-48](https://user-images.githubusercontent.com/46882964/54862205-41a2db00-4d5d-11e9-8d9b-470c04be22a3.png)

![2019-03-23_11-18-43](https://user-images.githubusercontent.com/46882964/54862218-73b43d00-4d5d-11e9-8bc7-eb9f9c472b92.png)

**Comment by mitulpanch** [comment]
Its Working

**Comment by ajayrajecb** [comment]
> 
> 
> Its Working

no, still its not working
