### ISSUE TITLE
In User Profile, message appeared ? what is the use of this ?

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#213]
In User Profile, message appeared ? what is the use of this ?

![2019-03-23_16-30-56](https://user-images.githubusercontent.com/46882964/54865350-3d40e700-4d8a-11e9-9ad8-b3bcc5cc6f14.png)

**Comment by mitulpanch** [comment]
Coming soon for notification
