### ISSUE TITLE
Tags on Account gets removed when page gets refreshed.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#216]
**To Reproduce**
1. Go to 'Account List Page'
2. Expand any Account.
3. Add Tag
4. Now, Refresh that page.

**Comment by mitulpanch** [comment]
Live pe tag ke liye kya role chahiye?
Role ka issue he

**Comment by mitulpanch** [comment]
Advance Role ke bad barobar kar raha he
so ither humko design change karna hoga ya fir Role

**Comment by risipatel** [comment]
Advance role ON ho ya Off, mein usi Accounts pe tag add kar pa rha hu jisme mein hu...

**Comment by risipatel** [comment]
Now, advance role ON ho ya Off sare Account pe tag add kar pa rha hu...

**Comment by risipatel** [comment]
#258
