### ISSUE TITLE
Help section click throws to wrong url in all pages

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#218]
When i click on help section bottom of the any page 404 page open
url is below
 https://user.ecbsdev.xyz/help/dashboard?acid=1

![2019-03-25_12-10-35](https://user-images.githubusercontent.com/46882964/54901414-608ba380-4efc-11e9-8e01-9a12b2abae5c.png)

**Comment by mitulpanch** [comment]
it is correct
just change devecbs to easycloudbooks
it will work on easycloudbooks
