### ISSUE TITLE
Doesn't allows the user with advance role to create voucher.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#219]
**Describe the bug**
I had not given any voucher role to myself, but given the advance role.

**Actual Result**
System doesn't allows to create the voucher.

**Expected behavior**
Should allow me to create voucher as I had advance role.

**Screenshots**
![Screenshot from 2019-03-25 14-05-28](https://user-images.githubusercontent.com/46882833/54905452-10660e80-4f07-11e9-90ca-7cf343732fd0.png)

**Comment by risipatel** [comment]
Few days back, I was able to create voucher with only advance role..

**Comment by mitulpanch** [comment]
Is it different from live?
I think Advance only gives right to change voucher role.

**Comment by risipatel** [comment]
On live,It allows to create a voucher with only advance role.

**Comment by mitulpanch** [comment]
Please resubmit if not done
Working on my side
