### ISSUE TITLE
UI issue on Account details page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#220]
**Describe the bug**
I have created Debtor with Other in relation field. Check the Unbilled Projects field in status bar.

**Screenshots**
![Screenshot from 2019-03-25 15-19-34](https://user-images.githubusercontent.com/46882833/54910888-3d202300-4f13-11e9-913a-471de1e5cc8e.png)

**Comment by mitulpanch** [comment]
not able to reproduce
