### ISSUE TITLE
Design issue on Accounts page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#223]
**Screenshots**
![Screenshot from 2019-03-25 17-23-01](https://user-images.githubusercontent.com/46882833/54917895-d4d93d80-4f22-11e9-97c4-b4592c61652f.png)

**Comment by mitulpanch** [comment]
Note length issue?

**Comment by risipatel** [comment]
Need to increase height of Note field's Text box. And width of whole popup.
