### ISSUE TITLE
Query Builder Page, total run column shows 0, which are not 0 on live

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#227]
Query Builder Page, Total run column shows 0, which are not 0 on live

![2019-03-26_17-38-37](https://user-images.githubusercontent.com/46882964/54996244-c5272b00-4fee-11e9-8507-3e729be2aab1.png)

**Comment by mitulpanch** [comment]
it is working
just starting with 0 again
