### ISSUE TITLE
Throws an error on click of save btn of Executive on roles page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#23]
Steps to reproduce:-
1. Open roles page.
2. Click on edit btn of Executive.
3. Click on Save btn.

![screenshot from 2019-01-25 10-27-51](https://user-images.githubusercontent.com/46882833/51726317-b83c9880-208c-11e9-9099-5514bdff9f36.png)

**Comment by mitulpanch** [comment]
Available from Version 5.0.6965.30948
