### ISSUE TITLE
Change Multiple options appears only once on Accounts.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#230]
**To Reproduce**
1. Go to 'Accounts page'
2. Select any two accounts of similar type. 
3. Click on Multiple tag btn.
4. Add tag on opened pop up.
5. Click on Save.
6. Now again select two accounts of similar type.

**Actual behavior**
Multiple edit btns row doesnt appears.

**Screenshots**
![Screenshot from 2019-03-27 13-04-40](https://user-images.githubusercontent.com/46882833/55058047-e7718500-5090-11e9-9a78-7d658227e034.png)

**Comment by risipatel** [comment]
Change multiple options appears on single selection.
![Screenshot from 2019-04-04 12-47-12](https://user-images.githubusercontent.com/46882833/55536598-cc79c300-56d7-11e9-9ead-15ec2403b159.png)

**Comment by mitulpanch** [comment]
that ok, No Problem
