### ISSUE TITLE
Documents, dont have delete role but button is active

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#231]
In documents. i don't have delete role but button is active there,
when i click , don't have enough privilege message appeared.

![2019-03-27_16-51-45](https://user-images.githubusercontent.com/46882964/55072706-cc633d00-50b1-11e9-9718-643bce800b05.png)

![2019-03-27_16-45-09](https://user-images.githubusercontent.com/46882964/55072731-df760d00-50b1-11e9-867d-400b7d0fa5f7.png)

**Comment by mitulpanch** [comment]
What was before in 4X version?

**Comment by ajayrajecb** [comment]
> 
> 
> What was before in 4X version?

On live same issue, delete button active without role, but when click don't have privilege message appeared.
