### ISSUE TITLE
Ashok Sir request to display contrary account name on Account Details Page. 

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#235]
Rather than displaying self name on Account details page, should diplay contrary account.

![Screenshot from 2019-03-28 12-48-40](https://user-images.githubusercontent.com/46882833/55138172-d3915600-5158-11e9-9890-57c372c6d6ae.png)

![Screenshot from 2019-03-28 12-48-42](https://user-images.githubusercontent.com/46882833/55138170-d2f8bf80-5158-11e9-80bc-f0f73cd7954f.png)

**Comment by mitulpanch** [comment]
Yes it a bug. On 4X version it is working correctly.
