### ISSUE TITLE
Should remove title field on Accounts page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#236]
**Describe the bug**
Title displays the name that is already written above.

**Screenshots**
![Screenshot from 2019-03-28 14-00-44](https://user-images.githubusercontent.com/46882833/55142247-2c192100-5162-11e9-80ab-c0a0fe9135a5.png)

**Comment by risipatel** [comment]
We can also remove Transaction, Price/Discount and Tax fields.
![Screenshot from 2019-03-28 15-59-28](https://user-images.githubusercontent.com/46882833/55150647-99cd4900-5172-11e9-97a8-7ed5d7bd0c30.png)

**Comment by mitulpanch** [comment]
@vinpahilwani Please Approve this

**Comment by vinpahilwani** [comment]
Approved : remove title, transactions count, price discount and tax on list page

**Comment by mitulpanch** [comment]
REmoved
