### ISSUE TITLE
Error while transferring Project to other user

### ISSUE THREAD

**Issue by kamalksquare** [EasyCloudConsultants/EasyCloudBooks#237]
**Describe the bug**
While I am trying to transfer any project to other user it got disconnected current session and it clears all filters and I am not able to transfer project as well. It happens to all other users also.

**To Reproduce**
1. Go to 'any project'
2. Click on 'icon of user's image to transfer project'
3. disconnected
4. clear all filters
5. connected again without filters

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome,
 - Version  73.0.3683.86 (Official Build) (64-bit)
![Screen Shot 1](https://user-images.githubusercontent.com/49016903/55151155-95556000-5173-11e9-82af-2091c0809b09.jpg)
![Screen Shot 2](https://user-images.githubusercontent.com/49016903/55151165-9be3d780-5173-11e9-8114-12209428f528.jpg)
![Screen Shot 3](https://user-images.githubusercontent.com/49016903/55151170-a00ff500-5173-11e9-9271-cd2f3b4daf48.jpg)

**Comment by mitulpanch** [comment]
Solved Now
