### ISSUE TITLE
Year period page, require all month list by default

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#239]
![2019-03-28_18-08-01](https://user-images.githubusercontent.com/46882964/55158250-74493b00-5184-11e9-9cd8-20e20af2d213.png)
 Need this list by default
Jan to Dec
Q1 to Q4
H1, H2

**Comment by mitulpanch** [comment]
It depends on last year added

**Comment by ajayrajecb** [comment]
> 
> 
> It depends on last year added

an to Dec
Q1 to Q4
H1, H2

its same for all CA firms, to please add it by default with current year, sothat when we setup its appeared automatic in year period section.

**Comment by mitulpanch** [comment]
it comes by default, if user change year / Period than that continues
