### ISSUE TITLE
"Reset from template" functionality works only once.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#24]
Steps to reproduce:-
1. Open ProjectDetailsPage.
2. Click on "Reset from template".
3. Click on cancel btn on opened window.
4.  Again click on "reset from template" btn.

Actual Result:-
Dropdown to select saved template remains disabled.

![screenshot from 2019-01-25 11-22-17](https://user-images.githubusercontent.com/46882833/51727805-b0342700-2093-11e9-9033-844aec0e6ef6.png)

**Comment by mitulpanch** [comment]
Solved in Version 5.0.6965.30948
