### ISSUE TITLE
Home dashboard, UI issue Team Members Status

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#245]
On live Team Members Status
![2019-03-29_13-57-52](https://user-images.githubusercontent.com/46882964/55219432-e8d6b500-522a-11e9-8963-56522492bbad.png)

On devecbs Team Members Status 
**Alignment issue**
![2019-03-29_13-58-30](https://user-images.githubusercontent.com/46882964/55219600-5551b400-522b-11e9-9690-0fc7bfec6cbd.png)

**Comment by risipatel** [comment]
Functionality Removed
