### ISSUE TITLE
Unable to upload file using drag and drop option in sub folder

### ISSUE THREAD

**Issue by kamalksquare** [EasyCloudConsultants/EasyCloudBooks#247]
**Describe the bug**
We are not able to upload any file in sub folder of any client using drag & drop option. However it could be uploaded using right click and upload option.

**To Reproduce**
1. Go to 'Documents Tab'
2. Search client.
2. Click on sub folder created in client's folder.
3. Upload any file using drag and drop option.
4. See error:- "Upload Folder/Subfolder not found"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version : Version 73.0.3683.86 (Official Build) (64-bit)
![SCREEN SHOOT 1](https://user-images.githubusercontent.com/49016903/55275022-bc439b80-5305-11e9-9651-33664c7cb55d.jpg)
![SCREEN SHOOT 2](https://user-images.githubusercontent.com/49016903/55275023-c06fb900-5305-11e9-9c0c-cbabf28bb86a.jpg)

**Comment by risipatel** [comment]
#153
