### ISSUE TITLE
Contact page click shortcut issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#248]
By Vinod sir

contact click shortcut should be according to image
![2019-04-02_10-32-02](https://user-images.githubusercontent.com/46882964/55378164-766d1a00-5535-11e9-96f9-f51afce03a3a.png)

**Comment by mitulpanch** [comment]
Other menus are currently hidden

**Comment by ajayrajecb** [comment]
> 
> 
> Other menus are currently hidden

@vinpahilwani
