### ISSUE TITLE
Project Page, Filtered view title issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#249]
By Vinod Sir

After apply filter title should be **Showing Filtered View**

![2019-04-02_10-39-21](https://user-images.githubusercontent.com/46882964/55378238-cc41c200-5535-11e9-9745-701b20cef75b.png)

Filter clear button are different colors, they should be same.

**Comment by mitulpanch** [comment]
it is there if you apply custom filter

**Comment by ajayrajecb** [comment]
> 
> 
> it is there if you apply custom filter

is it possible to available for search by company, search by service or other service ?
