### ISSUE TITLE
Contact Page, Images are distract design

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#250]
By Vinod sir,

Please see below image

![2019-04-02_10-48-36](https://user-images.githubusercontent.com/46882964/55378354-3ce8de80-5536-11e9-9e41-1635a23cd01b.png)

**Comment by mitulpanch** [comment]
woh images firse upload karni padegi
no other option

**Comment by ajayrajecb** [comment]
> 
> 
> woh images firse upload karni padegi
> no other option

@vinpahilwani
