### ISSUE TITLE
Need to add some text in pop up of Custom filter.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#251]
**Describe the bug**
Need to add text like select or select field. And Vinod sir had some visibility issue on custom filter pop up drpdwn.

**Comment by risipatel** [comment]
Kindly upload the screenshot of Custom filter pop up. @vinpahilwani

**Comment by mitulpanch** [comment]
> Need to add text like select or select field. 
Where?

**Comment by risipatel** [comment]
![Screenshot from 2019-04-02 16-32-04](https://user-images.githubusercontent.com/46882833/55397890-e9da5000-5564-11e9-9f23-91a5e4694c4d.png)

**Comment by mitulpanch** [comment]
plugin do not support adding text. apart from that anything
