### ISSUE TITLE
Need to change display text according to image on Add tag pop up.

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#252]
By Vinod Sir

Need to change display text according to image on Add tag pop up in all pages.

![2019-04-02_12-19-05](https://user-images.githubusercontent.com/46882964/55381967-129d1e00-5542-11e9-9f0d-bb30114d3bc1.png)

**Comment by risipatel** [comment]
Remove tag ka option hover karne pe aa rha hai, toh usko default view pe hi dikhana hai.. @mitulpanch 
![Screenshot from 2019-04-02 14-19-03](https://user-images.githubusercontent.com/46882833/55389765-7ed44d80-5553-11e9-99eb-db0cfb0e0cb9.png)

**Comment by ajayrajecb** [comment]
> 
> 
> Remove tag ka option hover karne pe aa rha hai, toh usko default view pe hi dikhana hai.. @mitulpanch
> ![Screenshot from 2019-04-02 14-19-03](https://user-images.githubusercontent.com/46882833/55389765-7ed44d80-5553-11e9-99eb-db0cfb0e0cb9.png)

@mitulpanch
