### ISSUE TITLE
Service Schedular Add Note is not working

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#257]
when i click on add note button , console show error

![2019-04-02_14-37-28](https://user-images.githubusercontent.com/46882964/55390669-4fbedb80-5555-11e9-8e75-ff117467a324.png)

![2019-04-02_14-37-00](https://user-images.githubusercontent.com/46882964/55390674-53526280-5555-11e9-89e0-2de62964664e.png)

**Comment by ajayrajecb** [comment]
Not working

**Comment by mitulpanch** [comment]
what the error coming?

**Comment by mitulpanch** [comment]
Ok, Working Now
