### ISSUE TITLE
Company page icons related issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#261]
![2019-04-02_16-03-22](https://user-images.githubusercontent.com/46882964/55398036-3160dc00-5565-11e9-8083-49686c0e1b45.png)

Sir wants to change icons

**Comment by mitulpanch** [comment]
Direction requires additional permission from user, and it costs x100 times more money than standard map

**Comment by ajayrajecb** [comment]
> 
> 
> Direction requires additional permission from user, and it costs x100 times more money than standard map

@vinpahilwani
