### ISSUE TITLE
Project List Page, due dates column missing

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#262]
On live its appear see below image,

![2019-04-02_14-23-19](https://user-images.githubusercontent.com/46882964/55398446-2bb7c600-5566-11e9-8384-fea1fdf6be02.png)

devecbs its not appear

**Comment by mitulpanch** [comment]
@vinpahilwani

**Comment by mitulpanch** [comment]
Required by @vinpahilwani 

Removed from Expanded view
Sorting also Added to List by Upcoming Due Date
