### ISSUE TITLE
Image overlaps on company name on Multiple project create page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#264]
![Screenshot from 2019-04-04 10-28-34](https://user-images.githubusercontent.com/46882833/55530654-9252f600-56c4-11e9-9a60-3db8e98661c3.png)

**Comment by mitulpanch** [comment]
is this still open?

**Comment by risipatel** [comment]
Now its proper.
![Screenshot from 2019-04-26 12-01-05](https://user-images.githubusercontent.com/46882833/56787719-05124580-681b-11e9-98bf-3e1b4239fa03.png)
