### ISSUE TITLE
Notification URL path related issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#266]
on click on notification url is https://www.devecbs.xyz/accounts.aspx?id=15&acid=74

https://www.devecbs.xyz/Accounts.aspx?an=1&mode=items&nfid=346711

https://www.devecbs.xyz/projects.aspx?an=1&nfid=346709
open 404 page

![2019-04-04_14-09-57](https://user-images.githubusercontent.com/46882964/55542291-5c256e80-56e4-11e9-945d-ad405c009eb0.png)

**Comment by mitulpanch** [comment]
Is this applicable for new Notification>
