### ISSUE TITLE
Staff Page related bug 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#273]
![2019-04-05_11-44-43](https://user-images.githubusercontent.com/46882964/55607503-fdbac780-5799-11e9-8990-eacf3438870e.png)

please see above Image for error

**Comment by mitulpanch** [comment]
Because new Help Section Uses Linux Server system,
Which do not support Localization and are Case-Sensitive, Regardless of Windows which support both by Default.

Any way we tried to redirect you to Actual Link which is Staff in this case, ( and not /staff).

**Comment by ajayrajecb** [comment]
> 
> 
> Because new Help Section Uses Linux Server system,
> Which do not support Localization and are Case-Sensitive, Regardless of Windows which support both by Default.
> 
> Any way we tried to redirect you to Actual Link which is Staff in this case, ( and not /staff).

@vinpahilwani
