### ISSUE TITLE
Need to change few things on ledger print page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#274]
Need to remove things that is in Red box. And Add/Update things written in Green box.

![2019-04-09_15-52-03](https://user-images.githubusercontent.com/46882833/55794467-edc91d80-5ae2-11e9-9a79-f8ccd61dbf2e.png)

**Comment by risipatel** [comment]
And Ashok sir requested to delete running balance. And display debit, credit and closing balance like below image.
![Screenshot from 2019-04-05 12-48-15](https://user-images.githubusercontent.com/46882833/55610792-504bb200-57a1-11e9-83be-822943a027b0.png)

**Comment by vinpahilwani** [comment]
approved

**Comment by sureshsirvi** [comment]
Further Changes required on account page
After settlement of transaction notes required to appear on screen, same as it appear for transaction settlement  ... 
<img width="1280" alt="Screenshot 2019-12-06 at 9 50 44 AM" src="https://user-images.githubusercontent.com/46813198/70295847-67e6a900-180e-11ea-9be6-e9192a3c90ff.png">

**Comment by sureshsirvi** [comment]
Transaction note required on TAX INVOICE PAGE:
<img width="1280" alt="Screenshot 2019-12-06 at 9 56 12 AM" src="https://user-images.githubusercontent.com/46813198/70295984-fc510b80-180e-11ea-925b-dfc68ebb8831.png">

**Comment by sureshsirvi** [comment]
Transaction note required on Receipt
<img width="1280" alt="Screenshot 2019-12-06 at 10 00 32 AM" src="https://user-images.githubusercontent.com/46813198/70296109-67024700-180f-11ea-9216-4b775e2856f0.png">
 PAGE:

**Comment by sureshsirvi** [comment]
Transaction NOTE and Receipt NUMBER required on Receipt Voucher.
<img width="1280" alt="Screenshot 2019-12-06 at 10 00 32 AM" src="https://user-images.githubusercontent.com/46813198/70296364-68803f00-1810-11ea-860f-7a4d543b1153.png">

**Comment by sureshsirvi** [comment]
Changes for Journal Voucher
<img width="1280" alt="Screenshot 2019-12-06 at 10 09 44 AM" src="https://user-images.githubusercontent.com/46813198/70296548-0c69ea80-1811-11ea-9c0f-c10177b15be8.png">

**Comment by sureshsirvi** [comment]
Changes on Payment Voucher
<img width="1280" alt="Screenshot 2019-12-06 at 10 14 11 AM" src="https://user-images.githubusercontent.com/46813198/70296707-679bdd00-1811-11ea-88ff-6b8148a7d4c0.png">

**Comment by sureshsirvi** [comment]
no suggestion given for which coding changes required.

**Comment by risipatel** [comment]
### Need to remove things that is in Red box. And Add/Update things written in Green box.
![image](https://user-images.githubusercontent.com/46882833/70414649-c1560e80-1a80-11ea-9157-c05c4f22fa76.png)

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/70713160-684ddb00-1d0b-11ea-80aa-ba17f303cce9.png)

**Comment by mitulpanch** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/46882833/70713160-684ddb00-1d0b-11ea-80aa-ba17f303cce9.png)

Tax Removed

**Comment by mitulpanch** [comment]
Sorry, My mistake--

 I thought you were talking about DateTime Pattern, ie. instead of APR to APRIL.

**Comment by risipatel** [comment]
### Resolved.. @vinpahilwani @sureshsirvi @ashokbhurani 
![image](https://user-images.githubusercontent.com/46882833/70799769-93e6c900-1dd0-11ea-94f2-c25426e3c21e.png)
