### ISSUE TITLE
Contacts and Companies Custom fields show in edit mode also

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#277]
In current system contacts and companies custom fields are not shown in edit mode.
sir wants to show custom field on edit mode also where user fill or edit custom fields and save them.

![2019-04-05_14-29-07](https://user-images.githubusercontent.com/46882964/55616667-f1da0000-57af-11e9-8405-f8d45ec8a2fa.png)

**Comment by mitulpanch** [comment]
Please Close

**Comment by mitulpanch** [comment]
Not coming
