### ISSUE TITLE
Doesn't allows to add custom field to the service.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#28]
**To Reproduce**
1. Go to Service Page.
2. Expand any service.
3. Select any Custom Field from the drop down.
4. Click on save btn.

**Actual Result**
Throws user to dashboard.

**Screenshots**
![screenshot from 2019-01-26 12-32-33](https://user-images.githubusercontent.com/46882833/51784638-07a8c480-2172-11e9-90c9-06f595a8f74a.png)

**Comment by mitulpanch** [comment]
Available from Version > 5.0.6965.29723
