### ISSUE TITLE
User Profile related issues

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#280]
1. Phone Verify Button is not working
![2019-04-05_14-59-52](https://user-images.githubusercontent.com/46882964/55618453-349dd700-57b4-11e9-80e8-7f8d63290d97.png)

2. Email notification is on but on view mode its show off
![2019-04-05_15-02-16](https://user-images.githubusercontent.com/46882964/55618486-48493d80-57b4-11e9-98dc-df8f9a1214d1.png)

**Comment by mitulpanch** [comment]
email is setting for primary email, not notification

**Comment by ajayrajecb** [comment]
> 
> 
> email is setting for primary email, not notification

?

**Comment by mitulpanch** [comment]
Attempted  to solve.

as templates still pending from textlocal i can not check it working

if still issue pin issue

**Comment by risipatel** [comment]
Nothing happened when I clicked on Verify btn.
![image](https://user-images.githubusercontent.com/46882833/61691787-f4099f80-ad49-11e9-9de8-5df782b1d12d.png)

**Comment by risipatel** [comment]
1. Verification of 1st number is verified still Verify btn is being displayed.
2. Verification of 2nd number is pending but system displays it as verified on my profile page.

![Screenshot from 2019-07-25 17-58-32](https://user-images.githubusercontent.com/46882833/61874520-3f68ad00-af06-11e9-9600-8ef47fb52336.png)
![Screenshot from 2019-07-25 17-50-10](https://user-images.githubusercontent.com/46882833/61874521-3f68ad00-af06-11e9-8fcb-d0a4876eef12.png)

**Comment by risipatel** [comment]
#503
