### ISSUE TITLE
Staff online status design related issues

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#282]
![2019-04-05_10-05-28](https://user-images.githubusercontent.com/46882964/55622157-0ec90000-57bd-11e9-9d7b-859ded15d20b.png)

Sir wants to see in normal text, small text (not bold)
1. Staff name
2. Working Company name 
3. Service
4. Year & Periods

In current status bar on mouse over some details from above list are available,
User wants to see above details, without mouse over if possible.

Like this, just example
![2019-04-05_10-05-28](https://user-images.githubusercontent.com/46882964/55622790-c90d3700-57be-11e9-997f-6b9bdcacfb5f.png)

**Comment by mitulpanch** [comment]
I think Title of Timesheet is more Important

**Comment by ajayrajecb** [comment]
> 
> 
> I think Title of Timesheet is more Important

@vinpahilwani
