### ISSUE TITLE
In project, save query gives error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#29]
**To Reproduce**
1. Go to 'Project page'
2. Click on 'Query'
3. Add some query and save
4. Error occurred
![querr](https://user-images.githubusercontent.com/46882964/51784897-0c6f7780-2176-11e9-9941-c9866c8a6ea2.png)
![queryrelated](https://user-images.githubusercontent.com/46882964/51784898-0c6f7780-2176-11e9-8106-80586de1df52.png)

**Comment by mitulpanch** [comment]
Query Page is not Ready Yet
