### ISSUE TITLE
POWERED BY GOOGLE DOES NOT SHOW GOOGLE ICON

### ISSUE THREAD

**Issue by vinpahilwani** [EasyCloudConsultants/EasyCloudBooks#291]
![2019-04-08_12-41-13](https://user-images.githubusercontent.com/46882964/55705507-8e90dd80-59fc-11e9-854f-2193f339773f.png)

**Comment by risipatel** [comment]
### Icon has been removed.
![Screenshot from 2019-06-13 11-21-40](https://user-images.githubusercontent.com/46882833/59406960-7444f880-8dcd-11e9-851f-5d6ced0321b0.png)
