### ISSUE TITLE
ON DOCUMENT PAGE ON RIGHT SIDE THERE IS SPACE FOR FILTER - WHICH IS BLANK 

### ISSUE THREAD

**Issue by vinpahilwani** [EasyCloudConsultants/EasyCloudBooks#292]
ON DOCUMENT PAGE ON RIGHT SIDE THERE IS SPACE FOR FILTER - WHICH IS BLANK , SHOW TEXT FILTER

**Comment by mitulpanch** [comment]
Image

**Comment by ajayrajecb** [comment]
> 
> 
> Image

![2019-04-08_12-39-12](https://user-images.githubusercontent.com/46882964/55705044-6fde1700-59fb-11e9-8ffb-453cbc147958.png)
