### ISSUE TITLE
Project Page, Status note text change issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#294]
Please Rename status note text "Client Status" to "Notify Client"

![Screenshot from 2019-04-08 10-39-12](https://user-images.githubusercontent.com/46882964/55700026-4cab6b80-59eb-11e9-8091-a8290166d2f3.png)

**Comment by mitulpanch** [comment]
It is not about Notify, Whenever Client Comes only he/she can view status

**Comment by ajayrajecb** [comment]
> 
> 
> It is not about Notify, Whenever Client Comes online he/she can view status

@vinpahilwani
