### ISSUE TITLE
Export functionality on documents page

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#296]
1. Two Export folders appeared
![2019-03-23_11-30-12](https://user-images.githubusercontent.com/46882964/54862375-ddcde180-4d5f-11e9-9f3d-8df0fa8e4254.png)

2. Exported file is not shown in folder in common documents and no email got regarding this export
![2019-03-23_11-32-13](https://user-images.githubusercontent.com/46882964/54862387-ffc76400-4d5f-11e9-9bb9-e4dd058662c9.png)

**Comment by mitulpanch** [comment]
Its solved now
Please Recheck
Old Folder will stay unless user deletes manually

**Comment by ajayrajecb** [comment]
Email related bug 

![2019-04-11_17-32-03](https://user-images.githubusercontent.com/46882964/55956224-11c26580-5c81-11e9-9a90-e11d840999ec.png)

**Comment by ajayrajecb** [comment]
![2019-04-11_17-59-44](https://user-images.githubusercontent.com/46882964/55957522-2f44fe80-5c84-11e9-8def-5c04de1ecd02.png)

Date decrease after every edit or save by one.
i type 11-04-2019, then its 10-04-2019, then 09-04-2019

**Comment by mitulpanch** [comment]
is solved for new quesries
