### ISSUE TITLE
Good Morning Message related issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#299]
gm message popup dot is by default on that's-why this is not disappeared after sometime.

![2019-04-09_10-18-08](https://user-images.githubusercontent.com/46882964/55774239-f48b6c80-5ab1-11e9-8dfd-034fee76a3be.png)

**Comment by mitulpanch** [comment]
removed sticky

**Comment by ajayrajecb** [comment]
> 
> 
> removed sticky

not solved
