### ISSUE TITLE
Projects Role Related issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#306]
I dont have Add Note Role in Project page,
i go to lead stage in project, click on change stage, msg popup appeared.
i type msg only not change stage. error occurs.

![2019-04-09_17-25-07](https://user-images.githubusercontent.com/46882964/55798758-62a15500-5aed-11e9-88cd-b3dd8a0acfe4.png)

**Comment by mitulpanch** [comment]
Retry as yesterday we have changed roles

**Comment by mitulpanch** [comment]
If no Error, Please Close Issue
