### ISSUE TITLE
Allows to ask/assign query to the person doesn't even have a role to open query page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#308]
**To Reproduce**
1. Go to Roles page.
2. Turn off your all the roles for Query page.
3. Now log in through different user's credentials
4. Go to Query Page.
5. Click on '+Create' button
6. Now assign that query to first user.

**Expected behavior**
Should display only those users who has atleast Query page open role.

**Screenshots**
![Screenshot from 2019-04-09 18-22-31](https://user-images.githubusercontent.com/46882833/55801793-7c926600-5af4-11e9-8c27-1acf8efb2150.png)

**Comment by mitulpanch** [comment]
Temporary closing issue. Feel free to reopen if required
