### ISSUE TITLE
Change Project Budget to 0 is not working

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#31]
Change Project Budget to 0 is not working
![bd0](https://user-images.githubusercontent.com/46882964/51786695-fa013800-218d-11e9-8926-d0a0d964b97e.png)
![b0c](https://user-images.githubusercontent.com/46882964/51786707-2917a980-218e-11e9-96af-d613a53db2dc.png)

**Comment by mitulpanch** [comment]
from Version 5.0.6965.30948
