### ISSUE TITLE
Role issue in Documents page

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#312]
I don't have Advance role in Documents page, but i open some companies which are not related to me., when i upload documents then message appeared You Don't Have Enough Privilege.

![2019-04-10_14-26-46](https://user-images.githubusercontent.com/46882964/55865832-c6cf2200-5b9c-11e9-9c8c-abd6336284ee.png)

![2019-04-10_14-48-48](https://user-images.githubusercontent.com/46882964/55867302-dd2aad00-5b9f-11e9-9c30-1c910919da6f.png)

**Comment by mitulpanch** [comment]
Duplicate #314
