### ISSUE TITLE
In Projects change due date popup issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#32]
1. Go to Project page
2. Open or view any project
3. Click on change due date icon 
4. Popup appear , cancel or cross button are not working
![ddpu](https://user-images.githubusercontent.com/46882964/51786822-d808b500-218f-11e9-8d3d-cff0b13ab93a.png)

**Comment by mitulpanch** [comment]
Solved in 5.0.6965.30948
