### ISSUE TITLE
System throws an error after choosing another in applies to.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#329]
**To Reproduce**
1. Go to 'Notifications Page'
2. Click on '+ Create' Btn
3. Select Project Alert In Applies to field.
4. Check Error.
5. Now try to select template.

**Screenshots**
![Screenshot from 2019-04-12 12-20-36](https://user-images.githubusercontent.com/46882833/56019055-53a2e880-5d21-11e9-9791-c7217c094f34.png)

**Comment by ajayrajecb** [comment]
Create Notification Functionality is not working, refresh button is not working, no sms send,

**Comment by ajayrajecb** [comment]
![2019-04-23_12-48-04](https://user-images.githubusercontent.com/46882964/56562030-19a9d000-65c6-11e9-8d7e-1d5e58b553d5.png)
