### ISSUE TITLE
In Project,List or view both mode, Unique id change is not working

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#33]
click on unique id for change it, type some alphabet and numeric number but system gives error popup message

![uid](https://user-images.githubusercontent.com/46882964/51787172-52d3cf00-2194-11e9-99de-a182c3877ff9.png)

**Comment by mitulpanch** [comment]
from  5.0.6965.30948

**Comment by ajayrajecb** [comment]
> 
> 
> from 5.0.6965.30948

not solve, after change it once, i try again to change it with alphabet but its not take abcd its only takes 1234

**Comment by ajayrajecb** [comment]
![2019-01-30_10-39-04](https://user-images.githubusercontent.com/46882964/51959718-c1a67600-247b-11e9-8597-7cdd4c77218f.png)

after page refresh its work

**Comment by ajayrajecb** [comment]
Reference error-
![2019-02-05_16-16-19](https://user-images.githubusercontent.com/46882964/52269236-89170880-2963-11e9-870e-180c4bd72e1e.png)
