### ISSUE TITLE
Year & Periods, in add new periods delete buttons appeared but cant work

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#331]
![2019-04-12_14-15-50](https://user-images.githubusercontent.com/46882964/56024926-b8187480-5d2e-11e9-803e-f4d0e42ed281.png)

and we discuss, Jan to Dec, Q1 to Q4, H1 H2 .by default fill ho k aayega, but nhi aa raha abhi.

**Comment by mitulpanch** [comment]
Please Recheck
