### ISSUE TITLE
Year & Periods edit mode bug

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#332]
![2019-04-12_14-34-58](https://user-images.githubusercontent.com/46882964/56025845-95875b00-5d30-11e9-8108-3c3a18172a55.png)

In edit mode periods delete button is not available, and when we erase text and try to save, 
text field is red appear.
live system period delete btn available in edit mode

**Comment by mitulpanch** [comment]
not able to reproduce
