### ISSUE TITLE
UI Issue on global search.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#335]
**Describe the bug**
While searching something, for few seconds system displays this.

![Screenshot from 2019-04-12 15-59-15](https://user-images.githubusercontent.com/46882833/56031934-6d065d80-5d3e-11e9-97b5-e6d03557e52c.png)

**Comment by mitulpanch** [comment]
Yes it is , in the,e this feature is there. when you search show color boxes. so implemented
