### ISSUE TITLE
Time tracker remains on even after logging out from ECB.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#34]
**To Reproduce**
1. Start the time tracker.
2. Logout from the ECB.
3. Again login.

**Expected behavior**
Should stop the time tracker when user logs out from the ECB.

**Comment by ajayrajecb** [comment]
still having same problem, not fixed

**Comment by vinpahilwani** [comment]
check whether it gets off after 5 min or not. I mean login after 6 min from logout

**Comment by ajayrajecb** [comment]
Time Tracker off after 6 min, i check. @risipatel please check once for confirmation.
