### ISSUE TITLE
Change Google account is not working 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#344]
Change Google account is not working 

![2019-04-16_15-59-09](https://user-images.githubusercontent.com/46882964/56202432-a69dd800-6060-11e9-8bec-57f643024584.png)

**Comment by mitulpanch** [comment]
Removed

**Comment by ajayrajecb** [comment]
> 
> 
> Removed

Required this button. its very useful for new users
