### ISSUE TITLE
Cancel btn on Pop up of timesheet page is not working.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#35]
**To Reproduce**
1. Go to 'Timesheet'
2. Start Time Tracker and wait for 10 minutes.
3. Click on the timesheet of current project.
4.  Popup to edit timesheet will appear.
5. Try to extend the timesheet of project which is running.

**Actual Result**
Cancel btn of Popup is not working.

**Screenshots**
![screenshot from 2019-01-29 11-43-21](https://user-images.githubusercontent.com/46882833/51887842-1b933700-23bb-11e9-8d67-2a522fa1b0df.png)

**Comment by ajayrajecb** [comment]
Goes into infinite buffering while trying to extend yesterday's timesheet.

![timst](https://user-images.githubusercontent.com/46882964/51888918-f05e1700-23bd-11e9-825a-2b2818e14005.png)

**Comment by risipatel** [comment]
Cancel btn issue is resolved. **But still goes into infinite buffering while extending the timesheet.**
