### ISSUE TITLE
Referral program needed in Easycloudbooks also.

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#357]
Referral program needed in Easycloudbooks also. like Expcon.

**Comment by mitulpanch** [comment]
Requirement - By @vinpahilwani 
-------------------------------
1. Referral Page in User Section
2. List of Companies which Requested with Referral Code
3. 1st Credit (500 Rs) after Company Created
4. 10% as Discount of Payment made by Company for 1 year Period from Company Createdate

**Comment by mitulpanch** [comment]
Email Template Required for Sharing.
Post it Here

**Comment by vinpahilwani** [comment]
Email Template


Hi

I am excited to share I’ve created created my Online Practice on Easycloudbooks- A practice management software that helps you save time by automating recurring administrative tasks. You can create practice with following link ——— and get credit of Rs. 1000 as reward credit. 


Thank you

(User Name)

**Comment by risipatel** [comment]
**Subject Line:** @username has invited you to Easycloudbooks- Practice Management Softaware.

**Comment by mitulpanch** [comment]
![Annotation 2019-12-11 103600](https://user-images.githubusercontent.com/5259926/71303809-e3864f80-23e3-11ea-9326-83f16d466980.jpg)


Please Provide this things

**Comment by mitulpanch** [comment]
new page
https://user.easycloudbooks.com/referral
