### ISSUE TITLE
Scheduler page, in weekly pattern problem occurs

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#360]
![2019-01-31_10-37-27](https://user-images.githubusercontent.com/46882964/56410422-b143b180-629a-11e9-959c-0ba34ca30d4e.png)

check box pe click nhi ho raha hai,  tick nhi ata;
color change bs hota hai, fir error message ata hai.
words pe click krne pe sb thik hai.

**Comment by mitulpanch** [comment]
Plugin error
