### ISSUE TITLE
Requirement in  Service page 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#370]
1. Service count needed
2. Paging Needed

![2019-04-22_15-06-15](https://user-images.githubusercontent.com/46882964/56495082-253bbf00-6512-11e9-8fd5-9cf117797ef9.png)

**Comment by mitulpanch** [comment]
paging nai hota service page pe

**Comment by ajayrajecb** [comment]
> 
> 
> paging nai hota service page pe

bahut jyada service ho jayengi to kya karenge fir ?
or Count kaise pata chalega kitni service hain isliye count chahiye tha.

**Comment by mitulpanch** [comment]
Page need complete redesign to do this.
Ask sir and if it is required then schedule work in milestone

**Comment by ajayrajecb** [comment]
> 
> 
> Page need complete redesign to do this.
> Ask sir and if it is required then schedule work in milestone

@vinpahilwani
