### ISSUE TITLE
Personal Gadgets, Query Builder Related issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#371]
![2019-04-22_16-11-52](https://user-images.githubusercontent.com/46882964/56497166-1d801880-651a-11e9-90e0-6fb205de7c6e.png)

Query Builder Search, arrow key clicks url is wrong, 
it should open related query builder with query.

**Comment by risipatel** [comment]
Throws user to Select Company.
https://user.easycloudbooks.com/selectcompany?returnurl=/QueryBuilder
![Screenshot from 2019-04-26 17-55-50](https://user-images.githubusercontent.com/46882833/56807474-9057ff00-684c-11e9-8e55-e6343a387fac.png)
