### ISSUE TITLE
UI issue on ecbmail pop up of Documents page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#375]
**Describe the bug**
1. Double cross icon is there.
2. Onfocus of text box, design gets lighter and on lost focus design gets highlighted.

**Screenshots**
![Screenshot from 2019-04-24 12-21-34](https://user-images.githubusercontent.com/46882833/56640437-aae57900-6690-11e9-890e-c472e37d01e3.png)

**Comment by risipatel** [comment]
![Screenshot from 2019-06-17 15-50-58](https://user-images.githubusercontent.com/46882833/59597580-c82a4700-9117-11e9-8896-f15919c2fbbe.png)

**Comment by mitulpanch** [comment]
its already perfect on live
