### ISSUE TITLE
In project page , show documents link is not working, document page is not open

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#38]
In project page, show documents button link is not working, document page is not open.

![show doc](https://user-images.githubusercontent.com/46882964/51969852-71d7a700-249b-11e9-8005-309ac264cbf8.png)

**Comment by ajayrajecb** [comment]
on click ,"invalid Token " popup appear

![2019-02-05_15-40-54](https://user-images.githubusercontent.com/46882964/52266577-c88e2680-295c-11e9-9a8c-3f92cbe4eb80.png)

**Comment by mitulpanch** [comment]
reload page
