### ISSUE TITLE
Changes on Settings Page

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#380]
1. GST on general/easycloudbooks tab
2. File validity link --> email/sms
3. Budget on new tab like general/easycloudbooks tab
4. Change name custom setting to Custom Key 
5. Remove Siteatclick setting  from settings
6. Payment Setting change to Online Payment settings
7. Allow HTML Email Content --> emai/sms

**Comment by risipatel** [comment]
Change Settings to Other Settings
![Screenshot from 2019-04-25 14-01-42](https://user-images.githubusercontent.com/46882833/56721513-ac7f7180-6762-11e9-9aed-8970195a761a.png)

**Comment by risipatel** [comment]
Need to change this to Setting
![Screenshot from 2019-04-26 11-18-47](https://user-images.githubusercontent.com/46882833/56786097-54557780-6815-11e9-842e-fc8a92c5be04.png)

**Comment by risipatel** [comment]
Change it to ECB Spend Limit
![Screenshot from 2019-04-26 11-22-47](https://user-images.githubusercontent.com/46882833/56786427-8fa47600-6816-11e9-89d8-1037fd62a063.png)

**Comment by vinpahilwani** [comment]
approve
