### ISSUE TITLE
WHEN I CLICK GLOBAL SEARCH CURSOR SHOULD BE ACTIVE

### ISSUE THREAD

**Issue by vinpahilwani** [EasyCloudConsultants/EasyCloudBooks#384]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mitulpanch** [comment]
Not Clear

**Comment by ajayrajecb** [comment]
> 
> 
> Not Clear

![2019-04-30_16-59-38](https://user-images.githubusercontent.com/46882964/56958964-85151400-6b69-11e9-9fa3-159ca40aa0bc.png)
