### ISSUE TITLE
Redirects to incorrect URL.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#388]
**Describe the bug**
Click on Help btn should redirect to https://help.easycloudbooks.com/user/Projects?ir=1.

![Screenshot from 2019-04-26 12-02-34](https://user-images.githubusercontent.com/46882833/56787966-bc0ec100-681b-11e9-9a50-e56bd1db32b8.png)

**Comment by Avinash-ecb** [comment]
help section me error nahi hai 
![image](https://user-images.githubusercontent.com/46588125/56796593-80322680-6830-11e9-8e57-b6d97f680cfe.png)

**Comment by Avinash-ecb** [comment]
Url me error hai

**Comment by risipatel** [comment]
Help of Automation page redirects user to https://help.easycloudbooks.com/user/notify/automation?ir=1 instead of **https://help.easycloudbooks.com/User/Automation?ir=1**
![Screenshot from 2019-04-30 14-35-13](https://user-images.githubusercontent.com/46882833/56951336-2e054400-6b55-11e9-9e6d-4190d6dca474.png)

**Comment by risipatel** [comment]
Help btn of Review and Finished Projects redirects user to Project Page.
### Present URL
Review Project:-https://help.easycloudbooks.com/User/Projects?ir=1
Finished Project:-https://help.easycloudbooks.com/User/Projects?ir=1

### Correct URL
Review Project:-https://help.easycloudbooks.com/User/ReviewProjects?ir=1
Finished Project:-https://help.easycloudbooks.com/User/FinishedProjects?ir=1

**Comment by risipatel** [comment]
Service Scheduler Redirects to wrong URL.
### Present URL
URL of **"i"** btn:-https://help.easycloudbooks.com/User/Servicescheduler?ir=1
URL of **Help** btn:- https://help.easycloudbooks.com/User/Services?ir=1
### Correct URL
URL of **"i"** btn:-https://help.easycloudbooks.com/User/ServiceScheduler
URL of **Help** btn:-https://help.easycloudbooks.com/User/ServiceScheduler

**Comment by risipatel** [comment]
Help page for Report is not there so it displays 404. Kindly display Coming Soon on Help page of Report If possible.

**Comment by risipatel** [comment]
Help Btn of Document log redirects user to https://help.easycloudbooks.com/User/Document?ir=1 instead of **https://help.easycloudbooks.com/User/DocumentLog?ir=1**

**Comment by risipatel** [comment]
Help btn of Query Builder page redirects user to Query page instead of Query Builder.
### Present URL
https://help.easycloudbooks.com/User/Query?ir=1
### Correct URL
https://help.easycloudbooks.com/User/QueryBuilder?ir=1

**Comment by risipatel** [comment]
URL of help btn on Notify Dashboard.
### Present URL
https://help.easycloudbooks.com/user/notify/notifydashboard?ir=1
### Correct URL
https://help.easycloudbooks.com/User/NotifyDashboard?ir=1

**Comment by risipatel** [comment]
**EMail Details page.**
### Present URL
https://help.easycloudbooks.com/user/notify/emaillog?ir=1
### Correct URL
https://help.easycloudbooks.com/User/EmailLog?ir=1

**Comment by risipatel** [comment]
**SMS Details page.**
### Present URL
https://help.easycloudbooks.com/user/notify/smslog?ir=1
### Correct URL
https://help.easycloudbooks.com/User/SMSLog?ir=1

**Comment by risipatel** [comment]
**Email Template page.**
### Present URL
https://help.easycloudbooks.com/User/Template?ir=1
### Correct URL
https://help.easycloudbooks.com/User/EmailTemplate

**Comment by risipatel** [comment]
**Create Notification page.**
### Present URL
https://help.easycloudbooks.com/user/notify/createnotification?ir=1
### Correct URL
https://help.easycloudbooks.com/User/CreateNotification?ir=1

**Comment by risipatel** [comment]
Click Help and i btn on Billing page redirects user to 404.

**Comment by risipatel** [comment]
### Service Scheduler Redirects to wrong URL.
**Present URL**
URL of "i" btn:-https://help.easycloudbooks.com/User/Servicescheduler?ir=1
URL of Help btn:- https://help.easycloudbooks.com/User/Services?ir=1

**Correct URL**
URL of "i" btn:-https://help.easycloudbooks.com/User/ServiceScheduler
URL of Help btn:-https://help.easycloudbooks.com/User/ServiceScheduler

### Help page for Report is not there so it displays 404. Kindly display Coming Soon on Help page of Report If possible.

### Click Help and i btn on Billing page redirects user to 404.

### Email Template page.
Present URL
https://help.easycloudbooks.com/User/Template?ir=1
Correct URL
https://help.easycloudbooks.com/User/EmailTemplate

### Help btn of Query Builder page redirects user to Query page instead of Query Builder. 
**Present URL** 
https://help.easycloudbooks.com/User/Query?ir=1
**Correct URL**
https://help.easycloudbooks.com/User/QueryBuilder?ir=1

### Help Btn of Document log redirects user to https://help.easycloudbooks.com/User/Document?ir=1 instead of https://help.easycloudbooks.com/User/DocumentLog?ir=1

**Comment by risipatel** [comment]
Still problem persists on Service Scheduler page.

**Comment by risipatel** [comment]
Billing Page Redirects to https://help.easycloudbooks.com/user/billing?ir=1 instead of  **https://help.easycloudbooks.com/User/Billing?ir=1**

**Comment by mitulpanch** [comment]
solved by 

> 
> 
> Billing Page Redirects to https://help.easycloudbooks.com/user/billing?ir=1 instead of **https://help.easycloudbooks.com/User/Billing?ir=1**

solved by @dharmendraecb
