### ISSUE TITLE
Fonts are different, in project page

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#392]
![2019-04-26_18-22-26](https://user-images.githubusercontent.com/46882964/56809198-ed55b400-6850-11e9-9f84-b3a60470f10d.png)
Project, contact and company page having this issue.
please do Fonts should be white in all ecb - suggested by rushi

**Comment by risipatel** [comment]
![Uploading image.png…]()
