### ISSUE TITLE
SERVICE Search not appear on Account Page to build New Query.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#399]
**Describe the bug**
<img width="1280" alt="Screenshot 2019-04-28 at 4 34 28 PM" src="https://user-images.githubusercontent.com/46813198/56863428-cbd10580-69d3-11e9-9212-896213f5e9b7.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by risipatel** [comment]
Hello Sir,
Technically, It is not possible to apply service related queries on Accounts page because they don't share any direct link.
