### ISSUE TITLE
Email Templates, refresh button is not working

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#401]
Email Templates, refresh button is not working

![2019-04-29_11-40-33](https://user-images.githubusercontent.com/46882964/56878945-2ae65700-6a74-11e9-80de-71da9cd4c017.png)

**Comment by risipatel** [comment]
Do we need refresh button? @ajayrajecb @vinpahilwani

**Comment by ajayrajecb** [comment]
I think , no need of this refresh button on this page.

**Comment by risipatel** [comment]
Refresh button is working now..
