### ISSUE TITLE
Contact page, Last name require minimum 4 characters

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#405]
![2019-04-29_14-09-55](https://user-images.githubusercontent.com/46882964/56884974-efa25300-6a88-11e9-97b4-e123ddde74dd.png)

### Contact last name is Das but its not save.

**Comment by mitulpanch** [comment]
@vinpahilwani @ajayrajecb @risipatel now requires only 1 character
