### ISSUE TITLE
Allows to overlap timesheet in multiple companies.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#413]
**To Reproduce**
1. Go to 'Timesheet' in one company.
2. Fill Timesheet for one day.
3. Now go to another company with same login
4. Now try to fill timesheet on same day and same time.

**Expected behavior**
Should not allow to overlap as it is not allowed when tracking the time with play btn.

**Screenshots**
### Raj Associate
![Screenshot from 2019-04-30 10-55-40](https://user-images.githubusercontent.com/46882833/56942204-00a99d80-6b37-11e9-9cd7-14e08ddc667b.png)
### ECB Funnel
![Screenshot from 2019-04-30 10-55-35](https://user-images.githubusercontent.com/46882833/56942207-01daca80-6b37-11e9-9f49-316b3bca790a.png)

**Comment by mitulpanch** [comment]
ok

**Comment by vinpahilwani** [comment]
we will do it later
