### ISSUE TITLE
Search by staff filter displays everyones position as Manager.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#415]
**Screenshots**
![Screenshot from 2019-04-30 13-53-47](https://user-images.githubusercontent.com/46882833/56948988-686be280-6b4f-11e9-866d-758ebcc3ca59.png)

![Screenshot from 2019-04-30 13-51-00](https://user-images.githubusercontent.com/46882833/56948934-4bcfaa80-6b4f-11e9-9a61-e030eac9184d.png)

**Comment by mitulpanch** [comment]
It is not position , its showing that user is watching other user with manager role

**Comment by ajayrajecb** [comment]
> 
> 
> It is not position , its showing that user is watching other user with manager role

@vinpahilwani

**Comment by risipatel** [comment]
Discussed with Vinod Sir, He has asked to Display only name of the user [remove Manager]. As only those users will be able to see others Timesheet who has Advance role of Timesheet.

**Comment by mitulpanch** [comment]
Role Removed

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/61623977-56549880-ac95-11e9-8334-6af4fe115ea2.png)
