### ISSUE TITLE
Email, SMS and API call count doesnt match at Admin and User site.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#420]
**Screenshots**
![Screenshot from 2019-05-01 10-56-32](https://user-images.githubusercontent.com/46882833/57006735-c4427400-6c00-11e9-951c-710f3fc92689.png)
![Screenshot from 2019-05-01 10-56-30](https://user-images.githubusercontent.com/46882833/57006736-c573a100-6c00-11e9-8038-b91e71b70f63.png)
### In fact, In every company Email and SMS count is same at Admin site.

**Comment by mitulpanch** [comment]
ok

**Comment by mitulpanch** [comment]
admin section is showing last 30 days, and billing section showing count according to billing period.
