### ISSUE TITLE
On roles page member count is incorrect.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#421]
### On role page, count of executive is 3, but on staff page it says there are only 2 executives.
![Screenshot from 2019-05-01 11-16-13](https://user-images.githubusercontent.com/46882833/57006980-d4f3e980-6c02-11e9-858a-ec2897e13cdd.png)
![Screenshot from 2019-05-01 11-16-16](https://user-images.githubusercontent.com/46882833/57006979-d45b5300-6c02-11e9-85f0-c4a3b4446567.png)

**Comment by mitulpanch** [comment]
MAster owner is counted in executive. as master owner is just a wrapper
