### ISSUE TITLE
Documents upload error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#425]
![2019-05-02_10-49-11](https://user-images.githubusercontent.com/46882964/57059487-41d6b480-6cd3-11e9-8990-b858e81d015c.png)
![2019-05-02_10-51-00](https://user-images.githubusercontent.com/46882964/57059488-426f4b00-6cd3-11e9-91ed-b97076314ebd.png)

**Comment by mitulpanch** [comment]
Due to Server Change Default Credential mis-matched.
Now from next time we are creating containers with default credentials, we can more specifically target container with storage service account
