### ISSUE TITLE
Created company without Unique Id.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#428]
**Describe the bug**
Because of the Import time error Company1 is been created without Unique Id. 

**Screenshots**
![Screenshot from 2019-05-03 17-48-50](https://user-images.githubusercontent.com/46882833/57138052-441e3900-6dcf-11e9-96c9-e04e78b359c0.png)

**Comment by risipatel** [comment]
And Company 1's account is not got created.

**Comment by mitulpanch** [comment]
ok
yeh company import jo pehle hamne try kiya useki wajah se hua
