### ISSUE TITLE
Design issues in Review Project page

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#43]
some images in review project page is broken, highlighted text in below image distract design

![2019-02-05_11-53-51](https://user-images.githubusercontent.com/46882964/52262461-8bbd3200-2952-11e9-9e7a-5caf798dd75a.png)

**Comment by mitulpanch** [comment]
Image will not come otherwise uploaded on new bucket

**Comment by ajayrajecb** [comment]
> 
> 
> some images in review project page is broken, highlighted text in below image distract design
> 
> ![2019-02-05_11-53-51](https://user-images.githubusercontent.com/46882964/52262461-8bbd3200-2952-11e9-9e7a-5caf798dd75a.png)

**Project In Progress Date** should be in single row. On live its in single row.
