### ISSUE TITLE
Doesn't allows to create project of newly created service.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#433]
**Describe the bug**
1. Created New service.
2. Then tried to Create project of it from projects page and Project Import page.

**Screenshots**
### Project Page
![Screenshot from 2019-05-07 10-16-28](https://user-images.githubusercontent.com/46882833/57272778-b4b8a480-70b2-11e9-8b74-bfb0113022e1.png)
### Project Import Page
![image](https://user-images.githubusercontent.com/46882833/57272895-30b2ec80-70b3-11e9-94cf-b37eb5040e1c.png)

### Team Page
![Screenshot from 2019-05-07 10-16-10](https://user-images.githubusercontent.com/46882833/57272769-acf90000-70b2-11e9-8755-2cd52dbcfb7a.png)

**Comment by mitulpanch** [comment]
Not able to reproduce

**Comment by risipatel** [comment]
Whenever new staff pr Service is created then it requires to be added into team. And system assigns/makes changes in teams, on page load event of Team page. So, temporary solution is that, whenever new service or user has been created then user has to open team page. #518
