### ISSUE TITLE
Redirects to old url on click of view btn of Document log.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#437]
**Describe the bug**
Redirects to https://user.easycloudbooks.com/user/Preview.html?acid=74.
**Screenshots**
![Screenshot from 2019-05-08 12-18-22](https://user-images.githubusercontent.com/46882833/57355351-72af6180-718b-11e9-8ae6-1f7217e791f2.png)

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/61625240-d976ee00-ac97-11e9-939c-9b1ea6c8b54a.png)

**Comment by mitulpanch** [comment]
that is actually microsoft error
sometimes we get  preview from microsoft/ sometimes not depending upon file type

image preview works perfectly as we are providing preview

**Comment by risipatel** [comment]
Still redirects to https://user.easycloudbooks.com/Preview.html?acid=74
![image](https://user-images.githubusercontent.com/46882833/61625471-7043aa80-ac98-11e9-88da-2935458b2d9a.png)

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/61631512-2f539200-aca8-11e9-997e-d20aad1d63fd.png)
