### ISSUE TITLE
New Company create - unique ID value not accepting shows error

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#444]
**Describe the bug**
<img width="1280" alt="Screenshot 2019-05-10 at 4 36 17 PM" src="https://user-images.githubusercontent.com/46813198/57523203-fa3ed100-7341-11e9-9b7f-a4608cd510ae.png">
![Uploading Screenshot 2019-05-10 at 4.36.08 PM.png…]()

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mitulpanch** [comment]
Old Company is keeping unique id
