### ISSUE TITLE
SMS and Email Count required per project.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#447]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by risipatel** [comment]
Displays Emails and SMS count of only last three months, Instead of that it should display overall count irrespective of some specific period.

**Comment by risipatel** [comment]
Please approve @vinpahilwani

**Comment by sureshsirvi** [comment]
REQUIRED URGENTLY

**Comment by mitulpanch** [comment]
Its already there. only showing when something is there.
Now added Notification Count to it

**Comment by mitulpanch** [comment]
#751 Created Quota increase request for sms / email
