### ISSUE TITLE
Multiple project creation screen - Service template name not showing properly

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#448]
**Describe the bug**
<img width="1280" alt="Screenshot 2019-05-14 at 12 11 38 PM" src="https://user-images.githubusercontent.com/46813198/57676176-910cd580-7641-11e9-93fc-b0ada101ef4d.png">

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/61575136-a7be2580-aae5-11e9-9330-691f8d007917.png)
