### ISSUE TITLE
During Create new contact , similar contacts popup issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#46]
1. Go to contact page
2. Click on Create new contact
3. fill first name single alphabet
4. similar contacts popup appear again & again. and profile picture broken design distract.

![2019-02-06_11-56-03](https://user-images.githubusercontent.com/46882964/52325171-16ad3380-2a0a-11e9-9357-5e1c3c07a7a6.jpg)

**Comment by mitulpanch** [comment]
Its working Correctly

**Comment by ajayrajecb** [comment]
> 
> 
> Its working Correctly

I type single word and this popup appeared, i erase that word but that popup appear again.
atleast i type 3 word then that popup will appear.

**Comment by ajayrajecb** [comment]
I type S popup appeared, then i erase S in first name fieldand click on middle name field pop up appear again

![2019-02-09_10-43-10](https://user-images.githubusercontent.com/46882964/52516843-c9be9c80-2c57-11e9-8a09-0fee0528e237.jpg)
