### ISSUE TITLE
New company Created but Year and period not auto created.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#461]
**Describe the bug**
<img width="1280" alt="Screenshot 2019-05-18 at 3 36 52 PM" src="https://user-images.githubusercontent.com/46813198/57968030-e66b1e80-7982-11e9-9c51-7079eeb08131.png">

**Comment by mitulpanch** [comment]
Takes 30 min OR nearest 00/30 min counter
