### ISSUE TITLE
Displays blank page while trying to edit schedular.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#47]
**To Reproduce**
1. Go to 'Scheduler' page.
2. Pick a scheduler whose create date is less than today.
3. Click on 'Edit btn' of that scheduler.

**Screenshots**
![screenshot from 2019-02-06 12-04-49](https://user-images.githubusercontent.com/46882833/52325094-cb932080-2a09-11e9-9e91-46297b022e1d.png)

**Comment by mitulpanch** [comment]
not able to reproduce

**Comment by risipatel** [comment]
**Steps To Reproduce:-**
1. Go to 'Scheduler' page.
2. Click on 'Edit btn' of that scheduler.
3. Click on 'See possible Items'.
4. Click on Cancel btn.
5. Now, Click on Edit btn of any Scheduler.

Actual Result:-
Takes user to the Possible Items Tab in Edit mode.

Expected Result:-
Should take user to General Tab in Edit mode.
