### ISSUE TITLE
Change text of company Excel download button to import company button

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#478]
![IMG-20190526-WA0000](https://user-images.githubusercontent.com/5259926/58377322-204bae80-7f9b-11e9-9bbf-a37db5db6b3d.jpg)

- vinod pahilwani

**Comment by mitulpanch** [comment]
It's download link for relative files

**Comment by mitulpanch** [comment]
![Annotation 2019-07-09 115029](https://user-images.githubusercontent.com/5259926/60864157-5f2e7e80-a240-11e9-851b-646531c97b70.jpg)

**Comment by risipatel** [comment]
Vinod Sir, Ajay Bhaiya and I had agreed on below.
![image](https://user-images.githubusercontent.com/46882833/60864372-08757480-a241-11e9-89cc-8d5f83a4a347.png)
