### ISSUE TITLE
Send btn is not working on Inquiry Page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#483]
**Describe the bug**
Send btn doesn't do anything on Inquiry form of Infosite.

![Screenshot from 2019-05-31 16-46-16](https://user-images.githubusercontent.com/46882833/58702634-ed068680-83c3-11e9-9bd7-6ef999db5b3c.png)

**Comment by ajayrajecb** [comment]
Name : Jessica Pierce
email : jessica.freshlakeonline@gmail.com
message : 
subject : Business Request
contactnumber : 08041740639

Message section is appear blank.
