### ISSUE TITLE
contact query builder

### ISSUE THREAD

**Issue by vinpahilwani** [EasyCloudConsultants/EasyCloudBooks#484]
![contacts query builder](https://user-images.githubusercontent.com/41849556/58742982-4fed3180-8447-11e9-9aca-7d2447018ab1.png)
display problem

![slect clear and new query](https://user-images.githubusercontent.com/41849556/58743019-d0139700-8447-11e9-842a-a90e11059ea6.png)

### what is use of select clear

**Comment by mitulpanch** [comment]
Removed
