### ISSUE TITLE
Todo completed count status not showing properly. number of pending todo appear as completed todo.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#486]
<img width="1280" alt="Screenshot 2019-06-04 at 10 26 12 AM" src="https://user-images.githubusercontent.com/46813198/58852259-70b9bf00-86b3-11e9-8ae6-f6c9b843dda7.png">

**Comment by mitulpanch** [comment]
@ajayrajecb Please recheck, Please pin if it is still issue.

**Comment by ajayrajecb** [comment]
solved
