### ISSUE TITLE
Creates shared schedulers even if user has chose Personal Scheduler.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#49]
**To Reproduce**
1. Go to 'Scheduler' page.
2. Click on 'Create Scheduler'.
3. Choose "Personal Scheduler" in Type Field.
4. Fill Correct data in remaining fields.

**Expected behavior**
Should create personal scheduler.

**Comment by risipatel** [comment]
Then, We should remove that DropDown from the design..

**Comment by mitulpanch** [comment]
its done 
in 5.0.20190206.1

**Comment by mitulpanch** [comment]
@sureshsirvi
