### ISSUE TITLE
OTP Login

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#490]
Required OTP Login 
User do not want to login to google account on someone's computer.

Resolution:
AuthCode integrated for each user.
one time setup required from user side.
any Authentication Code generation App can be used.

link:
https://www.easycloudbooks.com/AuthCode

**Comment by ajayrajecb** [comment]
When 1st time login , otp login page is not appear.
then logout and login again its appeared
