### ISSUE TITLE
After updating Name field in My Profile, it requires to logout and then login to display updated data.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#500]
![Screenshot from 2019-06-12 11-11-22](https://user-images.githubusercontent.com/46882833/59326547-7d1dc780-8d04-11e9-8ffc-253221b58084.png)

**Comment by risipatel** [comment]
### Actually First name and Last name gets reset from Google's data.
### Steps:
1. Go to 'My Profile'.
2. Edit your name.
3. Logout from ECB.
4. Login again using same account.
5. Go to My profile and check your name.

**Comment by mitulpanch** [comment]
FirstName and Lastname now detached  from google.

**Comment by mitulpanch** [comment]
Attempted to resolve logout/login name change issue

**Comment by risipatel** [comment]
Here it displays name as on google.
![Untitled](https://user-images.githubusercontent.com/46882833/61574071-e00a3780-aad6-11e9-8f28-5d8a98c01cfa.png)

**Comment by mitulpanch** [comment]
Ye baki he abhi
