### ISSUE TITLE
Displays team members in team which is removed from Staff.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#501]
Need to find scenario.

### Team Page
![Screenshot from 2019-06-12 10-29-25](https://user-images.githubusercontent.com/46882833/59324644-67f16a80-8cfd-11e9-885f-493a2e5f3832.png)

### Staff Page
![Screenshot from 2019-06-12 10-24-40](https://user-images.githubusercontent.com/46882833/59324390-5b204700-8cfc-11e9-81ad-dea7f7570433.png)

**Comment by mitulpanch** [comment]
can not solve without scenario

**Comment by risipatel** [comment]
Not able to reproduce..
