### ISSUE TITLE
Team page related bug

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#507]
ecc1.ecb1@gmail.com , this is not in staff but appear in default team dropdown.
![2019-06-17_15-11-07](https://user-images.githubusercontent.com/46882964/59595644-ceb6bf80-9113-11e9-88cb-e8af82646994.png)

**Comment by ajayrajecb** [comment]
#501

**Comment by risipatel** [comment]
Not able to reproduce
