### ISSUE TITLE
Global search displays extra records in result.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#508]
**Describe the bug**
Searched **risiecb@gmail.com**.
![Screenshot from 2019-06-17 15-52-53](https://user-images.githubusercontent.com/46882833/59597962-bac18c80-9118-11e9-828d-b2ea7a585505.png)

**Comment by mitulpanch** [comment]
matching ratio is currently 45 % 
"@gmail.com"
is making it to list
