### ISSUE TITLE
Sort by Email and Phone number is not working on Contacts Page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#510]
**Screenshots**
![Screenshot from 2019-06-17 16-11-19](https://user-images.githubusercontent.com/46882833/59598836-bac28c00-911a-11e9-958b-6d93fb1d3f9c.png)

**Comment by mitulpanch** [comment]
Not possible as multiple value possible for this.
Removed the sorting design
