### ISSUE TITLE
If there is any UnSettled receipt then that should be displayed irrespective of selected period.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#511]
**Describe the bug**
Presently Unsettled receipts are being displayed according to selected year.
**But Ashok Sir has requested that it should display data no matter if that receipt's date is in the future/present or Past.**

**Screenshots**
![Screenshot from 2019-06-17 16-32-00](https://user-images.githubusercontent.com/46882833/59600435-c87a1080-911e-11e9-950c-f939a03f5203.png)

**Comment by mitulpanch** [comment]
filter cannot be overridden for any partial field

**Comment by risipatel** [comment]
> filter cannot be overridden for any partial field

I believe we are doing that for current balance.

**Comment by mitulpanch** [comment]
yes current balance ke liye karte he (that is not count of objects), but you will lose actual filter based receipt count in process.
