### ISSUE TITLE
Service Page, clear text box issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#514]
![screencapture-user-easycloudbooks-Services-2019-06-17-18_05_37](https://user-images.githubusercontent.com/46882964/59604916-1e54b580-912b-11e9-9bff-047be579dc71.png)

**Comment by mitulpanch** [comment]
Its working on my side. Please recheck

**Comment by ajayrajecb** [comment]
now no need of this feature because market place import available soon.
so close this bug
