### ISSUE TITLE
SPPC is asking reminder mails sharing based on the position.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#517]
**Describe the bug**
Many of our clients are requesting that initial reminders/email/sms should go to the department head (say accounts/manager etc)
And if the matter is still pending, then the Escalated REMINDER should go to the Director.

![Screenshot from 2019-06-24 14-43-07](https://user-images.githubusercontent.com/46882833/60006591-65442d00-968e-11e9-9f2e-1df71d8d2cfa.png)

**Comment by mitulpanch** [comment]
already provided solution to @vinpahilwani

**Comment by risipatel** [comment]
QB has parameter saying 'Company User Relation: Position', but that parameter only helps us to filter the project, that parameter cant be used to decide whom to share a mail?
So, we might require an option to choose whom to share a mail while adding an action. @mitulpanch
