### ISSUE TITLE
New staff join issue, not reflect in project member while create new project

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#518]
1. new staff join.
2. its appear in default team.But
3. when we create new project, that member not appear in team members list of project.

**Comment by risipatel** [comment]
Whenever new staff pr Service is created then it requires to be added into team. And system assigns/makes changes in teams, on page load event of Team page. So, temporary solution is that, whenever new service or user has been created then user has to open team page.

**Comment by mitulpanch** [comment]
Currently annot fix, untill some new rules comes in for team/ default team setup.
Escalate to @vinpahilwani  if you want

**Comment by ajayrajecb** [comment]
> 
> 
> Currently cannot fix, untill some new rules comes in for team/ default team setup.
> Escalate to @vinpahilwani if you want

@vinpahilwani

**Comment by mitulpanch** [comment]
Cleared Setting Team, Default Team from everywhere.

Now setting Default Team only when,
1. Staff Joined
2. Service Created
