### ISSUE TITLE
Package Page- Image upload error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#522]
### after upload , url disappeared on edit (seedpackage page)
![2019-06-27_13-55-23](https://user-images.githubusercontent.com/46882964/60249949-63bf7280-98e3-11e9-9453-f8b67b8cd7d5.png)

![2019-06-27_13-59-27](https://user-images.githubusercontent.com/46882964/60250266-e6483200-98e3-11e9-8543-c45356609126.png)

### Default Image appeared, not which i upload !

**Comment by mitulpanch** [comment]
url kya dala he?

**Comment by ajayrajecb** [comment]
> 
> 
> url kya dala he?

https://storage.googleapis.com/ecb-client/72/Public/Canva - null.jpg

**Comment by ajayrajecb** [comment]
> 
> 
> url kya dala he?

Kisi bhi package me url image nhi aa rahi, default image appeared in all type Package we create

**Comment by mitulpanch** [comment]
link error tha
solved now
