### ISSUE TITLE
Package page filter requirement

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#523]
![2019-06-27_14-04-32](https://user-images.githubusercontent.com/46882964/60250716-c5341100-98e4-11e9-8983-f486942e95ee.png)

### In package filter 'Other' is not shown

**Comment by mitulpanch** [comment]
ok
adding today

**Comment by mitulpanch** [comment]
added

**Comment by ajayrajecb** [comment]
select Other and apply throws to 404 page
