### ISSUE TITLE
Seed Package Page, Create new scheduler type package is not available

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#525]
1. create new schedule package 
2. select group scheduler
3. Select Object, click + Add object
4. Drop down appear but scheduler not available in list

![2019-06-27_14-14-40](https://user-images.githubusercontent.com/46882964/60251821-e3027580-98e6-11e9-8f4d-1683808d642f.png)

### Required above image package name in drop down

**Comment by mitulpanch** [comment]
in second phase
