### ISSUE TITLE
Service Scheduler is not attached to Service.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#532]
**Describe the bug**
It had created Service Scheduler, Template and Query Builder but didn't attached service Scheduler to the Service.

**Screenshots**
![Screenshot from 2019-06-29 16-27-38](https://user-images.githubusercontent.com/46882833/60383139-db7bd180-9a8a-11e9-89f7-4319c6151d74.png)
![Screenshot from 2019-06-29 16-27-19](https://user-images.githubusercontent.com/46882833/60383140-db7bd180-9a8a-11e9-84aa-cc327c5a9f41.png)

**Comment by mitulpanch** [comment]
#532 is happening because of #533, both solved
