### ISSUE TITLE
Engine has Created duplicate Template while Importing Template.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#533]
**Describe the bug**

**Screenshots**
![Screenshot from 2019-06-29 16-24-01](https://user-images.githubusercontent.com/46882833/60383157-1c73e600-9a8b-11e9-9b2a-aee95e48272c.png)

**Comment by mitulpanch** [comment]
ha ye bhi solve kar diya he

**Comment by ajayrajecb** [comment]
> 
> 
> ha ye bhi solve kar diya he

still Not solve
