### ISSUE TITLE
Service page- Profit ratio related bug

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#538]
![2019-07-01_14-53-40](https://user-images.githubusercontent.com/46882964/60425827-01cb7980-9c11-11e9-8564-700b38a33fa2.png)

### 5. after edit it it becomes 0% again, its not save that value

**Comment by risipatel** [comment]
Max value it allows is 100.. @vinpahilwani

**Comment by vinpahilwani** [comment]
this is to be deleted as we discussed @mitulpanch
