### ISSUE TITLE
Income Account gets updated with package update

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#539]
**Describe the bug**

1. When seed package has no income account and importer has already Income acc in service then system does nothing.
2. When Seeded package has different income acc than Importer side then system updates the Income acc.

**Comment by risipatel** [comment]
According to me system should update Income Account only if that field is blank.

**Comment by vinpahilwani** [comment]
rishi ka sochna sahi hai. agar change karna mahenat ho to abhi jaisa hai woh bhi chalega.

**Comment by risipatel** [comment]
As discussed with Vinod sir, leaving it as it is..
