### ISSUE TITLE
In Documents page, contact email not updated 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#541]
### 4. old email shown, updated sachin mail not shown. see below picture

![2019-07-02_12-39-24](https://user-images.githubusercontent.com/46882964/60491934-811b8480-9cc7-11e9-85c2-d39f419e4c1c.png)

**Comment by mitulpanch** [comment]
Default contact/Company has no meaning to send email.
Now all emails coming from all contacts with send notification on.

**Comment by risipatel** [comment]
Displays emails of all the contacts attached with that company(whose notification is on).
