### ISSUE TITLE
Scheduler Page requirement, start date updated automatically after edit

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#544]
Scheduler Page requirement, start date updated automatically after edit
![2019-07-02_14-48-35](https://user-images.githubusercontent.com/46882964/60501462-b9c45980-9cd9-11e9-87ac-815c1288ac8c.png)

**Comment by risipatel** [comment]
### Not required any more, because now scheduler allows to create/edit scheduler with past date. @ajayrajecb
