### ISSUE TITLE
Service Page: Custom field auto populate not working.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#546]
**Describe the bug**

<img width="1280" alt="Screenshot 2019-07-02 at 7 41 35 PM" src="https://user-images.githubusercontent.com/46813198/60519610-885f8400-9d01-11e9-8da1-a8896c24ec76.png">

**Comment by risipatel** [comment]
Resolved by Mitul Sir.
