### ISSUE TITLE
Multiple project Creation, Status not change after creation project

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#548]
### While creating multiple projects, change status to Not Started, but after create project status not change, project goes to Lead
![2019-07-03_10-21-27](https://user-images.githubusercontent.com/46882964/60564471-61469800-9d7d-11e9-8dd7-de4eea9d271c.png)

**Comment by ajayrajecb** [comment]
After creation of project, this error message appeared
![2019-07-03_10-43-14](https://user-images.githubusercontent.com/46882964/60565027-850add80-9d7f-11e9-8a5e-30ee3fcfcd05.png)

**Comment by risipatel** [comment]
The issue over here is just that projects are created on lead even if user has specified some status while creating job.

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/70599679-bf708480-1c13-11ea-8c40-ce3ce169af95.png) @mitulpanch

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/70600123-f09d8480-1c14-11ea-85cc-a7d044d99a50.png)

**Comment by mitulpanch** [comment]
Background-color changed for Status Change

Status not Applied to Projects are not coming was the Error. User must apply status to project in order to Created project with desired Status
