### ISSUE TITLE
Displays service name instead of project title when user manually adds timesheet.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#557]
![image](https://user-images.githubusercontent.com/46882833/60718719-15dde680-9f43-11e9-9c18-b0705f9e59eb.png)

**Comment by risipatel** [comment]
Reported by Afsin.

**Comment by mitulpanch** [comment]
Vinod sir ne manga tha. becouse title koi dalta nai tha/Auto Created project esa aata he to pata nai chalta

**Comment by vinpahilwani** [comment]
mitul play button se jo aata hai waisa hi rakho 1. project : company name 2. status : company name 3. description : service
