### ISSUE TITLE
Need filters on Service Page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#562]

**Comment by risipatel** [comment]
Search By Name
Search By Group

**Comment by vinpahilwani** [comment]
name 
group
type
law
Recurring y n

**Comment by risipatel** [comment]
We have Search by Name, Search by Type and Search by Group.

**Comment by risipatel** [comment]
Law and Recurring pattern is not required. -On behalf  of Vinod Sir. @vinpahilwani

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/70844380-49b02700-1e66-11ea-861f-855a5f9e560c.png)
