### ISSUE TITLE
ECB Funnel Company only, Star Favorite functionality is not working

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#565]
### ECB Funnel Company only, Star Favorite functionality is not working in contact page
![2019-07-09_10-01-52](https://user-images.githubusercontent.com/46882964/60859894-d3155a80-a231-11e9-99d8-743accbf525d.png)

**Comment by mitulpanch** [comment]
Please recheck

**Comment by mitulpanch** [comment]
Not possible because of too much data,
You can escalate this issue
