### ISSUE TITLE
User Profile Edit , save is not working,Everything come from google

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#566]
### User Profile Edit , save is not working,Everything come from google,
![2019-07-09_10-13-10](https://user-images.githubusercontent.com/46882964/60860555-b29acf80-a234-11e9-862a-f6c9d20e63b9.png)

### If this edit is not working then give button which throws to google page where user update their name and picture

**Comment by risipatel** [comment]
Staff of AKT has said that they dont want to update name on google as they are using email ids like companyname_1@gmail.com, companyname_2@gmail.com. #500 @mitulpanch

**Comment by risipatel** [comment]
#500
