### ISSUE TITLE
Finished Projects count issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#57]
Only **7 projects** are shown.
actually above 10784 projects available in finished projects.
after cross click on clear filter 10784 projects appeared.

![2019-02-07_14-40-19](https://user-images.githubusercontent.com/46882964/52401030-c22bb600-2ae6-11e9-9ba2-75a6af2a352a.jpg)

**Comment by ajayrajecb** [comment]
Uncaught exception for same issue

![2019-02-07_15-26-54](https://user-images.githubusercontent.com/46882964/52403519-ebe7db80-2aec-11e9-9f23-5431e549cbe2.jpg)

**Comment by mitulpanch** [comment]
only last 30 day project appear by default
