### ISSUE TITLE
In review , Custom fields are displayed in alphabetical order instead of displaying it according to the priority.

### ISSUE THREAD

**Issue by amitkjainbaid** [EasyCloudConsultants/EasyCloudBooks#581]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by risipatel** [comment]
In Review stage, sorting of Custom field is being displayed in alphabetical order. That should be displayed  according to Priority given by user. @mitulpanch
