### ISSUE TITLE
Sending Project to review from completed, displays validation error.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#582]
**Describe the bug**
System throws an error when user tries to send project to review stage with putting some comments in status note.

**Screenshots**
![Screenshot from 2019-07-17 10-07-52](https://user-images.githubusercontent.com/46882833/61347739-adb0ce00-a87b-11e9-9fa0-6ef6f6c3aa1b.png)

**Comment by mitulpanch** [comment]
coming on 2019-07-19
