### ISSUE TITLE
Throws an error while using Email Notification filters in custom Filter.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#587]
### Query
![Untitled3](https://user-images.githubusercontent.com/46882833/61574837-9c1d2f80-aae2-11e9-8216-e79824c3e144.png)

![Untitled2](https://user-images.githubusercontent.com/46882833/61574839-9de6f300-aae2-11e9-9122-a8fbdf15a91b.png)
![Untitled1](https://user-images.githubusercontent.com/46882833/61574840-9f182000-aae2-11e9-8725-4939447069fc.png)

**Comment by mitulpanch** [comment]
Currently Query is not Supported.

**Comment by risipatel** [comment]
If it is visible there in list then some clients asks question about it and becomes difficult to answer them. If it is possible then we should hide those parameters which are not working. 
And hiding not working parameters might help clients to understand QB. @mitulpanch
