### ISSUE TITLE
Spelling mistake on Registration page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#598]
**Thank**
![image](https://user-images.githubusercontent.com/46882833/61698988-b1e75a80-ad57-11e9-938f-e7ff20ba0473.png)

**Comment by risipatel** [comment]
### There has to be back or close btn.

**Comment by risipatel** [comment]
**Not able to do free registration.**
![image](https://user-images.githubusercontent.com/46882833/61990806-d481b800-b064-11e9-9106-552c7c58a546.png)

**Comment by mitulpanch** [comment]
"Ok" button changed to "Explore EasyCloudBooks"
