### ISSUE TITLE
UI issue on staff invitation.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#600]
![image](https://user-images.githubusercontent.com/46882833/61767559-4a3a1980-ae02-11e9-9b76-99db8f2d5754.png)

**Comment by mitulpanch** [comment]
Photo not clear.Please upload larger image

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/61860700-01f52700-aee8-11e9-96b5-9ed49e942610.png)

**Comment by risipatel** [comment]
Now it displays correctly.
![Screenshot from 2019-07-25 14-47-25](https://user-images.githubusercontent.com/46882833/61862240-31f1f980-aeeb-11e9-9f2c-b656e87fb865.png)
