### ISSUE TITLE
Logo Is not appeared in email

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#609]
### Local image of logo uploaded in settings ECC but email not show logo
![2019-07-29_11-03-15](https://user-images.githubusercontent.com/46882964/62024008-ebedac00-b1f0-11e9-9b5b-a97c2a705a47.png)

![2019-07-29_11-07-53](https://user-images.githubusercontent.com/46882964/62024068-35d69200-b1f1-11e9-9353-3ccbf4f20931.png)

**Comment by risipatel** [comment]
Retested by Ajayraj.
