### ISSUE TITLE
System creates event of other type only in Automation.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#614]
**Describe the bug**
No matter what user chooses in category field while creating Event, System creates event of other type only. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46882833/62196691-19c32400-b39c-11e9-8003-78e00fba9873.png)

**Comment by ajayrajecb** [comment]
![2019-09-06_14-34-29](https://user-images.githubusercontent.com/46882964/64415777-9344e500-d0b3-11e9-99b1-04c121528c7a.png)
### Solved
