### ISSUE TITLE
Seeded four email templates but importer received 4 templates.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#615]
### Seeder Side
![image](https://user-images.githubusercontent.com/46882833/62210372-a03a2e80-b3b9-11e9-8f4c-f2d39f3e612c.png)

### Importer Side
![image](https://user-images.githubusercontent.com/46882833/62210435-c95abf00-b3b9-11e9-88a0-9bacacefe8c6.png)

**Comment by mitulpanch** [comment]
iske Seed PAckage me gadbad thi.
To test Please Recreate Seed PAckage
