### ISSUE TITLE
Custom fields required with Password storage facility to hide password as "******" 

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#624]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vinpahilwani** [comment]
Yes we should provide cutstom field type as password. 

while showing these fields it will display star and besides it there will be show button to display exact text of that field.
