### ISSUE TITLE
Filter to view deleted scheduler in not working.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#63]
**To Reproduce**
1. Go to 'Scheduler'.
2. Create one scheduler.
3. Now delete that scheduler.
4. Click on check box of deleted scheduler.

**Expected behavior**
Should display deleted projects.

**Screenshots**
![screenshot from 2019-02-07 16-30-09](https://user-images.githubusercontent.com/46882833/52407345-0e322700-2af6-11e9-9183-eb5466e03424.png)

**Comment by mitulpanch** [comment]
Only works for Deleted Items not for Schedulers
