### ISSUE TITLE
Schedular Page : not able to select Week day it show error see IMG

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#634]
<img width="1280" alt="Screenshot 2019-08-11 at 9 14 18 AM" src="https://user-images.githubusercontent.com/46813198/62829328-9e256a80-bc18-11e9-8f65-42851256ea4f.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by risipatel** [comment]
Its plugin issue. Kindly click on "Sun" to select Sunday, "Mon" to select Monday and so on. @sureshsirvi 
![Scheduler](https://user-images.githubusercontent.com/46882833/62845935-d779db00-bce9-11e9-8e5d-c64fb8e50091.png)

**Comment by risipatel** [comment]
#360
