### ISSUE TITLE
Even after refreshing the page, system keeps the last entered value in the filter.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#64]
**Description**
After refreshing the page system displays the entered value in the filter, but the result being displayed down there is not according the filter.

**To Reproduce**
1. Go to 'Projects page'
2. Enter some value in company field
3. Refresh the page.

**Expected behavior**
Either reset the filter or display result according to the filter.

**Screenshots**
![screenshot from 2019-02-08 10-59-28](https://user-images.githubusercontent.com/46882833/52460497-a4b32680-2b90-11e9-96c2-9be92ab70d89.png)

**Comment by risipatel** [comment]
Same thing happens on 

**Contact Page
Company Page
Project Page**

**Comment by mitulpanch** [comment]
I dont hink this is anything related to easycloudbooks. may be a browser cache issue. Please elobrate if it is related to us

**Comment by risipatel** [comment]
It resets all the filter on live version.
