### ISSUE TITLE
Notification of change log redirects to wrong URL.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#643]
![image](https://user-images.githubusercontent.com/46882833/63318249-78dcde80-c333-11e9-97fd-c2af3d48dc57.png)
### URL:- https://www.easycloudbooks.com/AccountPrint?type=lp&guid=changelog
![image](https://user-images.githubusercontent.com/46882833/63318257-81351980-c333-11e9-9f7f-a135cc5b705a.png)

**Comment by ajayrajecb** [comment]
solved by ajay, give wrong path thatswhy error occured.
