### ISSUE TITLE
Unbilled projects count doesn't match.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#651]
### Total Finished Projects Count
![image](https://user-images.githubusercontent.com/46882833/63666248-53951800-c7ec-11e9-9724-a4b03e7b53e9.png)

### Unbilled Projects Count
![image](https://user-images.githubusercontent.com/46882833/63666179-1cbf0200-c7ec-11e9-9cd7-b5b8c056bf75.png)

### Billed Projects count
![image](https://user-images.githubusercontent.com/46882833/63666035-8e4a8080-c7eb-11e9-8fdc-895546849b7a.png)

### Unbilled project according to gadget is 189
![image](https://user-images.githubusercontent.com/46882833/63666373-df0ea900-c7ec-11e9-9c61-9caee0dc4949.png)

### Unbilled projects according to accounts
![image](https://user-images.githubusercontent.com/46882833/63666424-1da46380-c7ed-11e9-9fbf-338fd5a27db8.png)

**Comment by mitulpanch** [comment]
Difference in 

Finished Project with Transaction Exists and Transaction down not Exist
is Projects which are Billed before Account Module Creation. 

This kinds of Projects are not coming if "Transaction Exist" filter is applied to stop duplication of billing.

--------------------

Account Project Unbilled count is according to Role and for Account Exists filter.
