### ISSUE TITLE
Need few parameter in query builder.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#652]
### Need parameter like month for the year..

![image](https://user-images.githubusercontent.com/46882833/63669823-bab8c980-c7f8-11e9-916a-dde6b94941fa.png)

**Comment by mitulpanch** [comment]
this parameter requires to return datetime.

Month of Year/Day return only number

We are comparing Result of Query to DateTime

**Comment by risipatel** [comment]
Not able to understand why this issue was created, So closing it..  -On behalf of Vinod Sir @vinpahilwani
