### ISSUE TITLE
Sales Voucher , print , Narration not appear in bill.

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#659]

**Comment by sureshsirvi** [comment]
It required urgently ... Also requested by some more people.

**Comment by mitulpanch** [comment]
![Annotation 2019-10-24 140156](https://user-images.githubusercontent.com/5259926/67467704-df99b380-f666-11e9-93e5-ca5d4f586294.jpg)

Note is coming in Template

**Comment by ajayrajecb** [comment]
![2019-10-24_14-24-34](https://user-images.githubusercontent.com/46882964/67469802-55ebe500-f66a-11e9-9066-d81974daa5fa.png)
### Please put this in account print setting bil print end section
