### ISSUE TITLE
In review Projects, Custom fields issue

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#66]
- When i move project completed to review, Boolean type custom field button off automatically, 
- Date type custom field value decrease by one(i type 14-03-1984, but its change after move 13-03-1984)
- Company type custom fields disappeared after move stage to review. 

![2019-02-08_16-21-49](https://user-images.githubusercontent.com/46882964/52477121-d21ac700-2bc6-11e9-9b2e-5acf3d06cd86.jpg)

**Comment by mitulpanch** [comment]
its on review page only or other pages too like project and Finished Project
?

**Comment by ajayrajecb** [comment]
1. goto project page, ON Boolean type custom field and save, 
2. after save Boolean button should be slide on right side but it move to left.

![2019-02-14_10-50-44](https://user-images.githubusercontent.com/46882964/52764696-2995b880-3047-11e9-9345-a87517b971bf.jpg)

problem exists in review and finished project
