### ISSUE TITLE
Staff page, time of invitation, requirement of staff name(Client Request)

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#661]
### Staff page, time of invitation, requirement of staff name, so that after join that name appear in staff list.

![staff](https://user-images.githubusercontent.com/46882964/64420907-fcc9f100-d0bd-11e9-82d2-ea32baafc73b.png)

**Comment by mitulpanch** [comment]
Not Possible
Name comes from Google Account, Later they can change from profile Page

Invitee can not decide user's name.

**Comment by ajayrajecb** [comment]
> Not Possible
> Name comes from Google Account, Later they can change from profile Page
> 
> Invitee can not decide user's name.

invitee just want to write name of staff which he sent request, which appeared in staff page
