### ISSUE TITLE
App Invite mail is not getting delivered.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#669]
### Email Log
![image](https://user-images.githubusercontent.com/46882833/65219174-ad2ff000-dad5-11e9-925d-0242aabb356d.png)
### SMS Log
![image](https://user-images.githubusercontent.com/46882833/65219180-b1f4a400-dad5-11e9-9760-c2194cfcf193.png)

**Comment by mitulpanch** [comment]
Removed only SMS
