### ISSUE TITLE
Broadcast Page, requirements

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#675]
### those buttons should go to email, sms and app notification page accordingly.
![2019-09-24_15-15-42](https://user-images.githubusercontent.com/46882964/65501875-60865380-dedf-11e9-811a-5c3ab7519269.png)

**Comment by mitulpanch** [comment]
not possible
Name change hone se pehle hi bola tha
"url change nai hoga"

**Comment by ajayrajecb** [comment]
> 
> 
> not possible
> Name change hone se pehle hi bola tha
> "url change nai hoga"

@vinpahilwani

**Comment by ajayrajecb** [comment]
### Paging Needed, some notification on 2nd page which are not shown,
please show latest sent on top of the list
