### ISSUE TITLE
Query Builder Parameter Required for App

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#676]
### and please sort contact on top which app is ON
![2019-09-24_17-23-48](https://user-images.githubusercontent.com/46882964/65510342-5588ee80-def2-11e9-87d3-e899d4b1eee3.png)

**Comment by risipatel** [comment]
Need parameter for-
Invitation acceptance Pending from Client side
Invited and installed app.

**Comment by mitulpanch** [comment]
ContactAppStatus new query parameter
