### ISSUE TITLE
Company page, Requirement for how many contacts use app

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#683]
### so please add column which show tick, refer below image for exp.
![2019-09-28_16-59-18](https://user-images.githubusercontent.com/46882964/65815832-f12b9f00-e211-11e9-8887-ef96bef5b447.png)

**Comment by vinpahilwani** [comment]
Yes good feature

**Comment by mitulpanch** [comment]
available on badge of contact

**Comment by mitulpanch** [comment]
i think we need to add badge  to contact in this view
