### ISSUE TITLE
Clients wants to enter exact decimal value (exp 1.011) in vouchers entry

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#688]
![2019-10-01_14-25-56](https://user-images.githubusercontent.com/46882964/65948347-b0bd6280-e457-11e9-9ef9-ec6b23287188.png)

Clients want decimal points entry in vouchers.(CA Amit Jain)

**Comment by vinpahilwani** [comment]
Not Required
