### ISSUE TITLE
Year & Periods appeared again after deletion

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#691]
In Raj Associates deleted some year and periods but after an hour login again all deleted year & periods appeared again.
![2019-10-10_16-45-13](https://user-images.githubusercontent.com/46882964/66564997-fc21f000-eb7e-11e9-9d5e-b2c3542d8443.png)

**Comment by mitulpanch** [comment]
Its is Linked to Year Start Date from Settings
It YearStartDate is  1st January it will Create Year as 2019 Jan, 2019 Feb
else 2019-20 Jan, 2019-20 Feb
