### ISSUE TITLE
Account Page : SETTLE button ERROR - At least 1 transaction required.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#696]
### Account Page : SETTLE button ERROR - At least 1 transaction required.
<img width="1280" alt="Screenshot 2019-10-12 at 8 48 58 AM" src="https://user-images.githubusercontent.com/46813198/66694075-942def80-eccd-11e9-80b1-95af89b80796.png">

**Comment by sureshsirvi** [comment]
at shows only when we select transaction by way of all selection. when we select one by one transaction it work proper.

**Comment by mitulpanch** [comment]
Solved possibly,
If still error pint it to priority
