### ISSUE TITLE
Image issue on project page company badge

### ISSUE THREAD

**Issue by SumitChavda** [EasyCloudConsultants/EasyCloudBooks#699]
### Man image is wrong, female image should appear.

![error](https://user-images.githubusercontent.com/56626357/66896615-c794b500-f012-11e9-8b2f-7a5f1dd37a5b.png)

**Comment by mitulpanch** [comment]
Its is showing.

Image Processing Takes little time

**Comment by ajayrajecb** [comment]
> 
> 
> Its is showing.
> 
> Image Processing Takes little time

solved now, how much time it will takes ?
