### ISSUE TITLE
Price field diplays 0 on accounts page.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#70]
**Screenshots**
![screenshot from 2019-02-09 16-10-06](https://user-images.githubusercontent.com/46882833/52519709-d2c66280-2c85-11e9-9a98-846faa99c430.png)

**Comment by risipatel** [comment]
Check Price and Tax fields in below images.
**ON ecbsdev**
![screenshot from 2019-02-25 14-28-59](https://user-images.githubusercontent.com/46882833/53326961-cd674a00-390c-11e9-8b36-a648ae3639b3.png)

**On Live**
![screenshot from 2019-02-25 15-57-44](https://user-images.githubusercontent.com/46882833/53331122-27204200-3916-11e9-9b69-36dabbd5feaa.png)

**Comment by mitulpanch** [comment]
Nice One. :)
TYpo mistake
