### ISSUE TITLE
Braodcast page click on blank page

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#702]
### Broadcast page click throws on blank page

![2019-10-24_18-18-28](https://user-images.githubusercontent.com/46882964/67487291-4a5ce600-f68b-11e9-9110-758367a6d06c.png)

![2019-10-24_18-21-16](https://user-images.githubusercontent.com/46882964/67487312-521c8a80-f68b-11e9-967c-1cc791892790.png)

**Comment by mitulpanch** [comment]
Notification mark as read not showing in lost
