### ISSUE TITLE
Invite staff blank email received by client staff 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#716]
![image](https://user-images.githubusercontent.com/46882964/68918316-a3ec9800-0793-11ea-9ee1-6665d73ded49.png)

### Staff got blank email of joining company email

**Comment by mitulpanch** [comment]
Not able to reproduce

No Error Log found at time of this Event(11:39 AM 14-11-2019)
Added Detail log in case this happens again

After this Second Email for same object, got every detail

This Error is not Recursive. Some exception made this.

I suggest we wait for re-occurrence
