### ISSUE TITLE
Need to add parameter in custom filter.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#717]
Need following parameters in Custom filter.
1. Turn Around Time
2. Turn Around Time Balance = TAT-NSIP
3. Budget Balance =Budget-Project Cost

**Comment by risipatel** [comment]
Can remove this parameter.
1. Is hidden
2. Target date.

**Comment by risipatel** [comment]
#710 #610  Need this as well.

**Comment by mitulpanch** [comment]
Provide Meaning

**Comment by mitulpanch** [comment]
**Requirement** : Any one active at a time for respective Object Type

**Comment by risipatel** [comment]
1. Note Overdue days.
2. Note upcoming days.

**Comment by risipatel** [comment]
We don't require this.
> 
> 
>     1. Note Overdue days.
> 
>     2. Note upcoming days.

**Comment by mitulpanch** [comment]
ok finalizing 
> 
> 
> Need following parameters in Custom filter.
> 
>     1. Turn Around Time
> 
>     2. Turn Around Time Balance = TAT-NSIP
> 
>     3. Budget Balance =Budget-Project Cost

**Comment by mitulpanch** [comment]
Turn Around Time = liking to Service Default TurnAroundTime
Turn Around Time Balance linking to Service.TurnArountTime - Project.NSIP
Budget Balance = Linking to Project.Budget - Project.Cost

**Comment by mitulpanch** [comment]
Problem is Service.TurnArountTime is variable,

Scenario : Service.TAT = 5 days
Project.NSIP = 2 days

so,
Project.TATB = 5 - 2 = 3 days(processed by Engine once, i guess)

now goto service page and change Service.TAT to 15 days

What ECB need to do in this case?

**Comment by mitulpanch** [comment]
as discussed with  @vinpahilwani 

Need Project.TAT as a separate column

Whenever a project gets created, value copied from service TAT.

**Comment by mitulpanch** [comment]
**Update**

Turn Around Time = liking to Project.TAT
Turn Around Time Balance linking to Service.TurnArountTime - Project.NSIP
Budget Balance = Linking to Project.Budget - Project.Cost

**Comment by mitulpanch** [comment]
QB Parameters:

1. ProjectExtraTurnAroundTime
2. ProjectExtraTurnAroundTimeRemaing
3. ProjectExtraBudgetBalance

**Comment by sureshsirvi** [comment]
@vinpahilwani 
1. Next note days
2. project create days

**Comment by risipatel** [comment]
### Need to add Days here. So that user can filter data by days from today.
![image](https://user-images.githubusercontent.com/46882833/69331035-14a32100-0c7a-11ea-9019-53ce834d076c.png)

**Comment by risipatel** [comment]
To filter future days user will mention positive number and to filter past days will user negative number. On behalf of Vinod. @vinpahilwani @mitulpanch

**Comment by mitulpanch** [comment]
![Annotation 2019-11-21 171544](https://user-images.githubusercontent.com/5259926/69335277-9303c100-0c82-11ea-97f6-cc72c9092e8b.jpg)

Don't need Project Parameters(i.e. Project.Budget, Project.BudgetBalance, Project.TurnArountTime, Project.TurnAroundTime Remaining),

Leave LastValue as it is already there on Gadgets.

Reason- Difficult to Understand
