### ISSUE TITLE
Priority Module - Key Notes

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#718]
Add All Keynotes here,
Feature Request,
Rule set,
When this should work
Timeout if any.

Engine Limitation etc.

**Comment by mitulpanch** [comment]
#717

**Comment by mitulpanch** [comment]
Max Default Value for Pass and Fail Filter is -99 to 99

**Comment by mitulpanch** [comment]
Max Calculated Value of any Object is -999 to +999

**Comment by mitulpanch** [comment]
Requirement : Active button/ Refresh Button triggers engine

**Comment by mitulpanch** [comment]
**Requirement** : Any one Priority is Active for respective Object Type

**Comment by mitulpanch** [comment]
**Requirement** :
![Annotation 2019-11-15 175937](https://user-images.githubusercontent.com/5259926/68943651-c30a1a80-07d1-11ea-97ca-57fa66cf2a49.jpg)

**Comment by mitulpanch** [comment]
Filters Required

**Comment by mitulpanch** [comment]
Is Reverse? Option to reverse Sort Order

**Comment by mitulpanch** [comment]
Maximum 10 Rules can be Added to Priority

**Comment by risipatel** [comment]
This would be a problem because there are more number of services. @vinpahilwani 
> 
> 
> Maximum 10 Rules can be Added to Priority

**Comment by mitulpanch** [comment]
**Give Input Project Filter.**

As last discussed on Friday 18th Nov, We want Projects with Completed or Below Stage. 

This filter will be applied by default. Custom Filter can not overwrite this.

**Comment by mitulpanch** [comment]
Update
@vinpahilwani 
All Projects which are not Finished

**Comment by risipatel** [comment]
Rather than restricting it by default we should leave to user.

**Comment by mitulpanch** [comment]
Please provide any Requirement about Engine, Priority, and Timings

**Comment by mitulpanch** [comment]
Engine Priority is 240
after all Project Related Events get Finished, so that it can assign priority. 
All new Projects have 10000 as Priority.
Still, we need to define when the "Reset Priority" event needs to be triggered after any Project related event.

**Comment by mitulpanch** [comment]
> 
> 
> **Requirement** : Max Calculated Value of any Object is -999 to +999

Now Leave as it is - @vinpahilwani

**Comment by mitulpanch** [comment]
What Default Priority of Project?

**Comment by mitulpanch** [comment]
Update 
Leave 10000 as Default Priority for New Projects
as discussed with @vinpahilwani

**Comment by mitulpanch** [comment]
Update 
**Requirement**
Scheduler required as client mat want to sent Priority on weekly or Monthly bases due to charges

Discussed with @risipatel, @vinpahilwani

**Comment by mitulpanch** [comment]
#727  Design Changes

**Comment by risipatel** [comment]
## Here we should restrict 0 as value when user selects divide or multiply.
> 
> 
> **Requirement** :
> ![Annotation 2019-11-15 175937](https://user-images.githubusercontent.com/5259926/68943651-c30a1a80-07d1-11ea-97ca-57fa66cf2a49.jpg)

**Comment by mitulpanch** [comment]
Without Executing QueryBuilder, System cannot identify that dividing or multiplying 0, though We return 0 in case of arithmetic error.

**Comment by risipatel** [comment]
### I believe this will become a common mistake that user would do if they are using divide and multiply. So, If we can help user here then we should do it.
# Priority
![image](https://user-images.githubusercontent.com/46882833/69421819-163b1a80-0d48-11ea-93b4-00d86204674a.png)

# Result
![image](https://user-images.githubusercontent.com/46882833/69421805-08859500-0d48-11ea-95f6-d02bd27c8d2c.png)
