### ISSUE TITLE
Attach case to voucher functionality is not working properly.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#72]
**Describe the bug**
Allows to attach the case, but after refreshing the page, project count changes to 0.

**To Reproduce**
1. Go to 'Accounts Page'
2. Click on 'View btn' of an account.
3. Attach case to the voucher.
4. Now refresh the page.

**Expected behavior**
Should store the value of project into database.

**Comment by mitulpanch** [comment]
Please Upload more details
Case / Project Attaching?

**Comment by risipatel** [comment]
**Describe the bug**
Allows to attach the **Project**, but after refreshing the page, project count changes to 0.

**To Reproduce**
Steps to reproduce the behavior:
    1. Go to 'Accounts Page'
    2. Click on 'View btn' of an account.
    3. Attach **Project** to the voucher.
    4. Now refresh the page.

**Expected behavior**
Should store the value of project into database.

**Project Attached to Voucher**
![screenshot from 2019-02-14 10-37-58](https://user-images.githubusercontent.com/46882833/52764123-be4ae700-3044-11e9-8137-d5b7be7f8df4.png)

**After Refreshing the Page**
![screenshot from 2019-02-14 10-46-36](https://user-images.githubusercontent.com/46882833/52764369-d1aa8200-3045-11e9-9cac-5fc911ee7ec0.png)

**Check project count in screenshot.**

**Comment by risipatel** [comment]
**Before attaching case to voucher**
Unbilled Project:- 1
Project column of Voucher:- 0
![screenshot from 2019-02-26 11-38-08](https://user-images.githubusercontent.com/46882833/53391022-107ff680-39bb-11e9-9901-a7e725654268.png)

**After attaching case to voucher**
 **Actual Result                                                      
Unbilled Project:- 1                                                      
Project column of Voucher:- 1                                    

Expected Result
Unbilled Project:- 1
Project column of Voucher:- 0**
![screenshot from 2019-02-26 11-39-29](https://user-images.githubusercontent.com/46882833/53391068-34433c80-39bb-11e9-8596-942855d5a32b.png)

**Requires to refresh to display correct result.**

**Comment by mitulpanch** [comment]
On my mistake.
I just thought its projects count error on transaction.
Account Detail was not getting updated.
Now its working correctly
