### ISSUE TITLE
THERE IS NO PITU VERMA IN OUR OFFICE. WHY IT IS NOT TAKING MAIN NAME AND TAKING GMAIL NAME INSTEAD

### ISSUE THREAD

**Issue by amitkjainbaid** [EasyCloudConsultants/EasyCloudBooks#720]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by risipatel** [comment]
Spoke with client and resolved this issue.. @amitkjainbaid @vinpahilwani
