### ISSUE TITLE
Need these UI changes on Priority page

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#727]
Scheduler:-
How often you want to reset the priority?

Is Reverse?
Turn ON this switch to display priority in Ascending Order of value.

QB:
Last Value
Number

Display scheduler above Is Active field. -On Behalf of Vinod Sir @vinpahilwani

**Comment by mitulpanch** [comment]
QB:
Last Value
Number
is not possible, it is mention number of times in code where difficult to search everywhere
