### ISSUE TITLE
### Need to add Days here. So that user can filter data by days from today.

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#729]
### Need to add Days here. So that user can filter data by days from today.
![image](https://user-images.githubusercontent.com/46882833/69331035-14a32100-0c7a-11ea-9019-53ce834d076c.png)

_Originally posted by @risipatel in https://github.com/EasyCloudConsultants/EasyCloudBooks/issues/717#issuecomment-557028563_

**Comment by risipatel** [comment]
1. Change Fixed to 'Fixed Date'.
2. And add 'Fixed Days'  -On Behalf of Vinod Sir. @vinpahilwani

**Comment by mitulpanch** [comment]
Fixed date is fixed and never change.
Fixed days will relate according to current date.

**Comment by mitulpanch** [comment]
Added to Fixed Category
