### ISSUE TITLE
Address data of Contact and Company is missing while exporting data.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#731]
Address data of Contact and Company is missing while exporting data

**Comment by mitulpanch** [comment]
Removed Primary Filter from Export,
Earlier it was set to return address only if address is primary.

additional-
setting address as primary if importing from excel and no address present for company or contact.

**Comment by risipatel** [comment]
### Filtered contacts where address is not empty. And in that query still it displays few contacts whose address is missing.
![image](https://user-images.githubusercontent.com/46882833/69847421-10d85580-129d-11ea-94dc-8469e2de97e6.png)

![image](https://user-images.githubusercontent.com/46882833/69847455-31081480-129d-11ea-97f5-8f01d0fc3c44.png)
