### ISSUE TITLE
Service Page : Required Facilities

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#732]
Features Required.
1. GROUP - Column Required
2. Filters Needed 
 a. Service Name
 b. Serice Type
<img width="1280" alt="Screenshot 2019-11-24 at 4 06 09 PM" src="https://user-images.githubusercontent.com/46813198/69493448-d0f82380-0ed4-11ea-9253-520fd91da4e9.png">

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by risipatel** [comment]
## Resolved
![image](https://user-images.githubusercontent.com/46882833/70700013-08960680-1cf0-11ea-865c-dd2d7f8af5ae.png)
