### ISSUE TITLE
Automation Page: Email templates not appearing 

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#733]
Only Global email templates appearing.. my personal email templates not showing here.
<img width="1280" alt="Screenshot 2019-11-24 at 9 34 22 PM" src="https://user-images.githubusercontent.com/46813198/69497402-a624c400-0f02-11ea-806f-b25d64797e73.png">
<img width="1280" alt="Screenshot 2019-11-24 at 9 34 27 PM" src="https://user-images.githubusercontent.com/46813198/69497403-a624c400-0f02-11ea-8e68-3e31423c1538.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by risipatel** [comment]
Sir On Automation Page, You have selected Company in applies to and all of your email templates are of project.. That's why you're not able to see your templates. @sureshsirvi
