### ISSUE TITLE
Filtered contacts where address is not empty. But in the result still it displays few contacts whose address is missing.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#740]
### Filtered contacts where address is not empty. And in that query still it displays few contacts whose address is missing.
![image](https://user-images.githubusercontent.com/46882833/69847421-10d85580-129d-11ea-94dc-8469e2de97e6.png)

![image](https://user-images.githubusercontent.com/46882833/69847455-31081480-129d-11ea-97f5-8f01d0fc3c44.png)

_Originally posted by @risipatel in https://github.com/EasyCloudConsultants/EasyCloudBooks/issues/731#issuecomment-559672535_

**Comment by mitulpanch** [comment]
Query CompanyAddress ka he

**Comment by risipatel** [comment]
Sorry, My bad..
