### ISSUE TITLE
Need to display last receipt date on Settled Vouchers.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#747]
Here, Instead of present date we need to display dates according to following rules.

1. If it is Debtor Acc then display Last Receipt Date.
2. If it is Creditor Acc then display Last Payment Date.
3. If Receipt/Payment voucher is not present there then display latest date.

**Note: Keep settlement date in backend no need to display it on voucher.**

![image](https://user-images.githubusercontent.com/46882833/70299046-c402fa80-1819-11ea-8547-cabd144b939b.png)

**Comment by risipatel** [comment]
4. If there is Payment and Receipt in settlement then display date of latest Receipt and Payment. @mitulpanch @vinpahilwani

**Comment by vinpahilwani** [comment]
> 1. If there is Payment and Receipt in settlement then display date of latest Receipt and Payment. @mitulpanch @vinpahilwani

not required - already covered in above rules

**Comment by risipatel** [comment]
### Here it should display 12-Dec-2018.
![image](https://user-images.githubusercontent.com/46882833/70684496-59940380-1ccc-11ea-8e80-6e876a44c765.png)

**Comment by mitulpanch** [comment]
I got confused between  Create Date and Invoice date, initially it was Create Date.
now changed to Invoice Date of Transaction

**Comment by risipatel** [comment]
Sort Order Issue..
![image](https://user-images.githubusercontent.com/46882833/70688703-5e5eb480-1cd8-11ea-8e93-f6e797b7fd88.png)

**Comment by mitulpanch** [comment]
Order is for Settlement Create Date

Sort / Filter should not be deppendent on child items.
in this case to sort date field system need to do following things.
Get Settlement > get all Transaction > check Account Type (above 3 condition) > then sort by condition for all invoice date

this is time consuming for no of rows

still required then please reply to this thread

**Comment by risipatel** [comment]
#### According to me, the whole point of this issue was to help user to find settled voucher using important dates.. And now we are not displaying vouchers in appropriate order. And not even providing an option to filter or sort them..
> 
> 
> Sort Order Issue..
> ![image](https://user-images.githubusercontent.com/46882833/70688703-5e5eb480-1cd8-11ea-8e93-f6e797b7fd88.png)

**Comment by vinpahilwani** [comment]
abhi i dont think we need this let users use this
