### ISSUE TITLE
Need to display opening balance on Print Ledger.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#749]
When user clicks on Print button then ECB redirects user to a print page where default Unsettled transaction are being displayed. There we need to display Opening Balance on top of unsettled transactions.

![image](https://user-images.githubusercontent.com/46882833/70310254-3208eb00-1835-11ea-89d8-16e5dd46b857.png)

**Comment by risipatel** [comment]
#274

**Comment by mitulpanch** [comment]
by default full ledger aata he
is liye opening balance nai dikhahe..

filter change karne pe startdate/enddate attach ho jati he.
so opening balance aa jata he

anyway change default behavior to last year

**Comment by sureshsirvi** [comment]
when click on print button.... print ledger should show the filtered date as we have applied on account page.
