### ISSUE TITLE
Documents Page, file upload error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#75]
1. goto documents section
2. type any company name and open it
3. try to upload files by browse or drag and drop
error occurred

![2019-02-11_13-55-27](https://user-images.githubusercontent.com/46882964/52552289-a5082780-2e05-11e9-9885-394f43751ac5.jpg)

**Comment by ajayrajecb** [comment]
all documents functionality throws above error

**Comment by ajayrajecb** [comment]
Files drag and drop upload , no file upload after drag and drop. File Upload error 
![2019-02-15_11-11-55](https://user-images.githubusercontent.com/46882964/52836918-a346a880-3112-11e9-9dad-09a20041e861.jpg)

**Comment by mitulpanch** [comment]
Working Now in 5.0.20190220.1 @ajayrajecb @dharmendraecb
