### ISSUE TITLE
SMS / Email / Notification Auto Delete Period

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#751]
SMS / Email / Notification Auto Delete Period is Currently 3 month due to too much data and Speed associated with its table.

ex. 1 email saves almost 20 rows of data.

**Requirement**

Client wants 1 year of back data.

**Comment by mitulpanch** [comment]
Ok now not Deleting data for 1 Year.

still need to think about too much data

**Comment by sureshsirvi** [comment]
we need at least 1 year log for mail sms and notification ...
