### ISSUE TITLE
Need few changes in Invoice Print.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#754]
## 2. Replace Year with Period
![image](https://user-images.githubusercontent.com/46882833/70412357-a2547e00-1a7a-11ea-997a-ae141ffc1a13.png)

**Comment by mitulpanch** [comment]
Duplicate Project with same Service will Create confusion without UniqueId

**Comment by sureshsirvi** [comment]
UniqueId is required..... it helps to find out identical projects when we have same service projects with same period .... like

Service like "E-way Bill" we creates multiple duplicate projects in one months i.e. daily invoice wise projects for E-waybill...

**Comment by ashokbhurani** [comment]
@sureshsirvi : please explain how it help you when we already have facility of project title

**Comment by sureshsirvi** [comment]
yes we can also manage from TITLE of project also... we can remove it.

**Comment by mitulpanch** [comment]
@vinpahilwani recommends-

Removing UniqueId
