### ISSUE TITLE
Need this changes in print view of Ledger.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#755]
### Need to remove things that is in Red box. And Add/Update things written in Green box.
![image](https://user-images.githubusercontent.com/46882833/70414649-c1560e80-1a80-11ea-9157-c05c4f22fa76.png)

_Originally posted by @risipatel in https://github.com/EasyCloudConsultants/EasyCloudBooks/issues/274#issuecomment-563096798_

**Comment by risipatel** [comment]
#746

**Comment by mitulpanch** [comment]
Currently 
![Annotation 2019-12-11 103600](https://user-images.githubusercontent.com/5259926/70593185-0e152300-1c02-11ea-9332-d79e0b4be2d7.jpg)

this things are dynamic on different things like
Account Type, Period, No of Vouchers etc.

still you want, Reply to this Thread

**Comment by mitulpanch** [comment]
`<div style="text-align: center;width:100%"><span style="font-size:18px;"><strong>LEDGER ([@obj_SelectedPeriod])</strong></span></div>
`

can be added for Ledger and Selected Period as Title in Account Pring

**Comment by risipatel** [comment]
Spoke with @ashokbhurani and @vinpahilwani.. They need this as it is.. 
> 
> 
> Currently
> ![Annotation 2019-12-11 103600](https://user-images.githubusercontent.com/5259926/70593185-0e152300-1c02-11ea-9332-d79e0b4be2d7.jpg)
> 
> this things are dynamic on different things like
> Account Type, Period, No of Vouchers etc.
> 
> still you want, Reply to this Thread

**Comment by risipatel** [comment]
Ok, we can display it with left align along with selected period.. On behalf of Ashok Sir & Vinod Sir @vinpahilwani @ashokbhurani
> 
> 
> `<div style="text-align: center;width:100%"><span style="font-size:18px;"><strong>LEDGER ([@obj_SelectedPeriod])</strong></span></div> `
> 
> can be added for Ledger and Selected Period as Title in Account Print
> 
> this is also Applicable to Other Print Types

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/70610582-d6ba6c80-1c29-11ea-8cb6-bc24130a5ab4.png)

**Comment by mitulpanch** [comment]
`[@obj_selectedperiod]` is key to add period in PrintHead
