### ISSUE TITLE
removed staff appeared everywhere ecc1.ecb1

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#771]
### Removed staff appeared everywhere **ecc1.ecb1(Sachin singh)**, filters, team, projects, accounts everywhere
![2019-12-12_10-55-35](https://user-images.githubusercontent.com/46882964/70685564-cbba1780-1ccf-11ea-91d6-18f5cae57f8a.png)

**Comment by mitulpanch** [comment]
Removed this staff manually.

I dont know that how this is staff of acid=74.

may be i have removed him from database directly for testing.
