### ISSUE TITLE
QueryBuilder - Check Dependency before Deleting 

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#774]
Please list down usage of Query Builder on pages
so that we can build dependency for Deleting QB.

**Comment by mitulpanch** [comment]
1. Automation
2. Broadcast
3. Priority
4. Dashboard Gadget

**Comment by mitulpanch** [comment]
5. Service Scheduler

**Comment by mitulpanch** [comment]
6. Export

**Comment by ajayrajecb** [comment]
### when i try to delete dependent query-builder, message appeared.
![2019-12-13_17-35-33](https://user-images.githubusercontent.com/46882964/70799283-356d1b00-1dcf-11ea-844e-3d67b9f36fa5.png)

**Comment by mitulpanch** [comment]
Message changed
