### ISSUE TITLE
Scheduler - Check Dependency before Deleting 

### ISSUE THREAD

**Issue by mitulpanch** [EasyCloudConsultants/EasyCloudBooks#775]
Please list down usage of Scheduler on pages
so that we can build dependency for Deleting Scheduler.

**Comment by mitulpanch** [comment]
1. Automation
2. Priority
3. Service Scheduler
4. Gadgets

**Comment by mitulpanch** [comment]
5. Dashboard

**Comment by risipatel** [comment]
Need to remove fields that are in red box and need display depended items in column. 
![image](https://user-images.githubusercontent.com/46882833/71236603-64cadd00-2325-11ea-822e-c43dad01fb16.png)

**Comment by mitulpanch** [comment]
Dependency pe sort nai ayega

**Comment by mitulpanch** [comment]
done

**Comment by ajayrajecb** [comment]
![2019-12-20_16-19-00](https://user-images.githubusercontent.com/46882964/71250633-285ba900-2346-11ea-82d4-3d2478c76ac3.png)
