### ISSUE TITLE
UI changes on print Page

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#776]
![image](https://user-images.githubusercontent.com/46882833/70701395-498f1a80-1cf2-11ea-9523-26180ceb96c5.png)

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/70701116-d38ab380-1cf1-11ea-95e6-af37863de814.png)

**Comment by mitulpanch** [comment]
> 
> # Need to display Apr 1, 2019
> 
> ![image](https://user-images.githubusercontent.com/46882833/70701116-d38ab380-1cf1-11ea-95e6-af37863de814.png)

----------------------------------------
this is already there, 
Go to Other Settings - Default Date Format - change Format to "August 06, 1959".
-------------------------------------------------
You can provide me settings, if any other date time pattern is required.

**Comment by risipatel** [comment]
### From now, new users will get this by default in Ledger Print Head, And for old user they have to change it manually in their Setting.
LEDGER
([@obj_selectedperiod])

From:[@ecbCompanyName][@ecbCompanyAddressLine1] [@ecbCompanyAddressLine2][@ecbCompanyAddressLandmark], [@ecbCompanyAddressCity][@ecbCompanyAddressPincode], [@ecbCompanyAddressState]P: [@ecbCompanyuserPhone]GSTIN : [@site_GSTNumber] | To:[@ecbAccountName] ([@ecbAccountType])[@ecbClientCompanyName][@ecbClientCompanyAddressLine1] [@ecbClientCompanyAddressLine2][@ecbClientCompanyAddressLandmark], [@ecbClientCompanyAddressCity][@ecbClientCompanyAddressPincode], [@ecbClientCompanyAddressState]P: [@ecbClientuserPhone]GSTIN : [@ecbClientCompanycf-GSTIN]
-- | --

**Comment by risipatel** [comment]
# Instead of Mar 31 it should display Apr 1.

> 
> 
> > # Need to display Apr 1, 2019
> > ![image](https://user-images.githubusercontent.com/46882833/70701116-d38ab380-1cf1-11ea-95e6-af37863de814.png)
> 
> ## this is already there,
> Go to Other Settings - Default Date Format - change Format to "August 06, 1959".
> 
> You can provide me settings, if any other date time pattern is required.

**Comment by mitulpanch** [comment]
**Sorry, My mistake**--

I thought you were talking about DateTime Pattern, ie. instead of APR to APRIL.

**Comment by mitulpanch** [comment]
Ok Solved now,

Still, this is a problem, not for Indian customers, but we may need to reset this for the global environment as it is a bit difficult to find timezone on Client PC without any context.

**Comment by mitulpanch** [comment]
![Annotation 2019-12-10 125905](https://user-images.githubusercontent.com/5259926/70881287-04206500-1ff2-11ea-92ac-7ee8dd90a261.jpg)

default settings changed to this.

**Comment by risipatel** [comment]
### Resolved
![image](https://user-images.githubusercontent.com/46882833/71576143-9148db00-2b15-11ea-
8fba-7308f5a43bd1.png)
