### ISSUE TITLE
Transaction NOTE and Receipt NUMBER required on Receipt Voucher.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#782]
Transaction NOTE and Receipt NUMBER required on Receipt Voucher.
<img width="1280" alt="Screenshot 2019-12-06 at 10 00 32 AM" src="https://user-images.githubusercontent.com/46813198/70296364-68803f00-1810-11ea-860f-7a4d543b1153.png">

_Originally posted by @sureshsirvi in https://github.com/EasyCloudConsultants/EasyCloudBooks/issues/274#issuecomment-562429156_

**Comment by risipatel** [comment]
### 1. If there is bank account[BA & BOA] involved in voucher then display Bank Receipt.
### 2. If there is Cash account involved in voucher then display Cash Receipt.
### 3. If both cash and bank accounts are involved then display Bank total and Cash total separately.

![image](https://user-images.githubusercontent.com/46882833/70795165-34cf8700-1dc5-11ea-8a64-f1ce3aedcb0b.png)

**Comment by risipatel** [comment]
Waiting for @sureshsirvi sir's approval..

**Comment by mitulpanch** [comment]
![Annotation 2019-12-11 103600](https://user-images.githubusercontent.com/5259926/71400906-3105f500-264e-11ea-968e-205ef20be6b6.jpg)

**Comment by mitulpanch** [comment]
> 
> ### 1. If there is bank account[BA & BOA] involved in voucher then display Bank Receipt.
> ### 2. If there is Cash account involved in voucher then display Cash Receipt.
> ### 3. If both cash and bank accounts are involved then display Bank total and Cash total separately.
> 
> ![image](https://user-images.githubusercontent.com/46882833/70795165-34cf8700-1dc5-11ea-8a64-f1ce3aedcb0b.png)

is done

**Comment by risipatel** [comment]
Alignment issue is there in print.
![image](https://user-images.githubusercontent.com/46882833/71403987-5b0fe500-2657-11ea-8da1-05df23447a29.png)

**Comment by risipatel** [comment]
### Resolved
> 
> 
> Alignment issue is there in print.
> ![image](https://user-images.githubusercontent.com/46882833/71403987-5b0fe500-2657-11ea-8da1-05df23447a29.png)
