### ISSUE TITLE
Changes for Journal Voucher

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#783]
Changes for Journal Voucher
<img width="1280" alt="Screenshot 2019-12-06 at 10 09 44 AM" src="https://user-images.githubusercontent.com/46813198/70296548-0c69ea80-1811-11ea-9c0f-c10177b15be8.png">

_Originally posted by @sureshsirvi in https://github.com/EasyCloudConsultants/EasyCloudBooks/issues/274#issuecomment-562430015_

**Comment by risipatel** [comment]
### 1. Remove things that are in Red Box.
### 2. Remove Pay Button.
![image](https://user-images.githubusercontent.com/46882833/70790679-97bc2080-1dbb-11ea-8023-02eb7b8fc4d1.png)

**Comment by risipatel** [comment]
Waiting for @sureshsirvi sir's approval..

**Comment by mitulpanch** [comment]
- Removed Pay button on JV Voucher
- Removed Closing Balance from all vouchers

**Comment by risipatel** [comment]
### Resolved
![image](https://user-images.githubusercontent.com/46882833/71576223-e97fdd00-2b15-11ea-9a51-d5eb810fdddc.png)
