### ISSUE TITLE
Throws exception when user tries to search file in entire company.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#806]
### Tried to  search this.
![image](https://user-images.githubusercontent.com/46882833/71638977-ef033180-2c93-11ea-9954-00528aecfe35.png)
### Result
![image](https://user-images.githubusercontent.com/46882833/71638961-8ddb5e00-2c93-11ea-88ea-e5ae6b71fa7b.png)

**Comment by mitulpanch** [comment]
limited support

works only for upto 1000 file

**Comment by risipatel** [comment]
#### Requires to refresh page to display actual content of the folder.

**Steps to Reproduce:-**
1. Go to any sub-folder.
2. Search Png files in entire company.
3. Now click on root folder.

![image](https://user-images.githubusercontent.com/46882833/71652929-7b265f00-2d4f-11ea-9124-6ab93c1b0293.png)
