### ISSUE TITLE
Before merging two folders we should ask user.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#811]
### On live, for same situation ECB opens up these popup.
![image](https://user-images.githubusercontent.com/46882833/71873178-95dc4780-3144-11ea-8be1-e336ef0c7b24.png)

**Comment by mitulpanch** [comment]
yeh popup bandh kiya hua he
for some reason

kyu bandh kiya woh nai likha he

koi reason hoga use time

**Comment by mitulpanch** [comment]
removing bug, as it is off intentionally
