### ISSUE TITLE
System ignores the amount of settled vouchers in Status bar of an Account.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#82]
**Description**
System reduces the amount from status bar when user settles Sales, JV, CN, DN, Payment and Receipt vouchers.

**To Reproduce**
1. Go to 'Accounts Page'.
2. Create a voucher with debtor in debit side.
3. Check the amount of Sales on status bar of that account.
4. Now settle that voucher.

**Expected behavior**
Reduces the amount from the status bar.

**Screenshots**
![screenshot from 2019-02-11 17-52-57](https://user-images.githubusercontent.com/46882833/52562881-e90b2480-2e25-11e9-8bfd-d99b7129ff0e.png)

**Comment by mitulpanch** [comment]
Settle Voucher is not doing anything in terms of accounting

**Comment by risipatel** [comment]
If we are settling the sales voucher then it should not make any difference in the **Sales** field of the Status bar..
**But right now it reduces the amount from the status bar, which shouldn't happen.**
