### ISSUE TITLE
Displays Easycloudbooks in title.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#831]
![image](https://user-images.githubusercontent.com/46882833/74233171-3697c700-4cf0-11ea-8496-035fa179a435.png)

**Comment by risipatel** [comment]
### In User profile it still displays easycloudbooks in title.
![image](https://user-images.githubusercontent.com/46882833/75540182-89d47e00-5a41-11ea-8187-8eba6157fb21.png)

**Comment by mitulpanch** [comment]
Solved

**Comment by risipatel** [comment]
![image](https://user-images.githubusercontent.com/46882833/75875687-2fb92b80-5e3a-11ea-935a-16a74ac8bcb0.png)
