### ISSUE TITLE
Allows to store sub-domain which is not available.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#836]
**To Reproduce**
1. Go to 'Website setting' page
2. Enter new sub-domain.
3. Click on save btn.
4. Now enter previous domain in sub-domain field.
5. Click on Save btn.

**Expected behavior**
Should not to save when user has entered invalid sub-domain.

**Screenshots**
![image](https://user-images.githubusercontent.com/46882833/74318982-335e1300-4da4-11ea-9405-4ea56700bf4b.png)

**Comment by mitulpanch** [comment]
Not able to  reproduce

**Comment by risipatel** [comment]
### Displays valid domain when user enters current domain.
![image](https://user-images.githubusercontent.com/46882833/75949720-20cf8900-5ecd-11ea-88b4-4e7eef6a4d71.png)

**Comment by risipatel** [comment]
> 
> ### Displays valid domain when user enters current domain.
> 
> ![image](https://user-images.githubusercontent.com/46882833/75949720-20cf8900-5ecd-11ea-88b4-4e7eef6a4d71.png)

## Not causing any problem so closing this issue.
