### ISSUE TITLE
Search by company filter gives error in Query Page

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#85]
Search by company filter gives error

![2019-02-12_18-08-57](https://user-images.githubusercontent.com/46882964/52636158-d3fbc780-2ef1-11e9-8f29-6533536bf399.jpg)

**Comment by mitulpanch** [comment]
Its something else. as far as Filter is working

**Comment by ajayrajecb** [comment]
> 
> 
> Its something else. as far as Filter is working

ok but company search drop down gives irrelevant name

![2019-02-13_12-14-12](https://user-images.githubusercontent.com/46882964/52692209-4b306a80-2f89-11e9-9fef-36c9e6b79acf.jpg)

**Comment by mitulpanch** [comment]
Its also searching companies contact names

**Comment by mitulpanch** [comment]
@sureshsirvi , @vinpahilwani 
Give your Views
Do you Require this ? or should I remove it as it will cost you processing time..!

**Comment by mitulpanch** [comment]
Removed

**Comment by sureshsirvi** [comment]
drop down not needed.. as per my view.
