### ISSUE TITLE
In query view mode some issues 

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#87]
1. Heading title is wrong- Create Query
2. Back button is not working
3. Project view button is not working.
4. Design is not proper.

![2019-02-13_10-23-29](https://user-images.githubusercontent.com/46882964/52688496-bc1d5580-2f7c-11e9-8b4d-9f94c30cf851.jpg)

**Comment by ajayrajecb** [comment]
Console error

![2019-02-13_10-41-38](https://user-images.githubusercontent.com/46882964/52688651-51b8e500-2f7d-11e9-892e-4fd0794bec32.jpg)

**Comment by ajayrajecb** [comment]
Same problems occurs in query closed stage also.

**Comment by ajayrajecb** [comment]
Design issue, kindly see live query page for reference, all Titles should be Bold.
![2019-02-21_12-55-06](https://user-images.githubusercontent.com/46882964/53151097-49ddee00-35d8-11e9-84df-fd75202a5e21.png)

**Comment by mitulpanch** [comment]
UI issue on Query Page  is OK
Later Stages, As this page is going to CRASH in short Future
