### ISSUE TITLE
unique ID is showing duplicate / invalid, however there is no same unique ID present. image attached.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#89]
<img width="1280" alt="screenshot 2019-02-13 at 2 18 27 pm" src="https://user-images.githubusercontent.com/46813198/52698988-b6366d00-2f9a-11e9-95dc-4b3c905a5a2e.png">
<img width="1280" alt="screenshot 2019-02-13 at 2 17 54 pm" src="https://user-images.githubusercontent.com/46813198/52698989-b6cf0380-2f9a-11e9-9b2f-a3d342525fe6.png">

**Comment by ajayrajecb** [comment]
Edit Unique Id in company page, gstn0145,  gives error
![2019-02-21_12-20-54](https://user-images.githubusercontent.com/46882964/53149815-db4b6100-35d4-11e9-809c-29933d52e408.png)
