### ISSUE TITLE
1st name , last name does not take 4 characters , invalid message appear. Required validation popup (red focus on that error field is not appear)

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#9]
In contact first name, middle name, last name warning popup required, like "single alphabet is not allowed for that field" or validation alert required. #8

**Comment by ajayrajecb** [comment]
> 
> 
> Accept in 5.0.6965.30948

red focus on that error field is not appear still

**Comment by mitulpanch** [comment]
Single Alphabet is allowed now for middle name

**Comment by ajayrajecb** [comment]
1st name , last name does not take 4 characters , invalid message appear. 

![2019-02-07_12-50-59](https://user-images.githubusercontent.com/46882964/52396216-0e6efa00-2ad7-11e9-970a-420c0647fd7f.jpg)
