### ISSUE TITLE
Company Page Issue: How to remove only one TAG. Some times we need to remove only particular tag.

### ISSUE THREAD

**Issue by sureshsirvi** [EasyCloudConsultants/EasyCloudBooks#94]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
<img width="1280" alt="screenshot 2019-02-13 at 3 47 21 pm" src="https://user-images.githubusercontent.com/46813198/52704687-2b0fa400-2fa7-11e9-8cdb-9d45a4783447.png">

**Comment by risipatel** [comment]
#560
