### ISSUE TITLE
Whenever Company is created, System creates an account for every company which doesn't have an account.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks#95]
**To Reproduce**
1. Go to 'Accounts page'.
2. Close one account from the list.
3. Now go to 'Company's page'.
4. Create one company.
6. Now check the account

**Comment by mitulpanch** [comment]
It is like that
@vinpahilwani @sureshsirvi  Please help on what is possible


as it was required before to create all account which are possible to create if setting is ON

**Comment by risipatel** [comment]
As discussed, Shouldn't create Account for those companies which doesn't have any account in closed State.

**Comment by mitulpanch** [comment]
Ok, Changing few things, 
At time of Creating Company, only created company gets account ,

rest work will be done through engine

**Comment by risipatel** [comment]
Engine has created Account for companies who has closed account.
![Screenshot from 2019-04-27 17-04-22](https://user-images.githubusercontent.com/46882833/56849150-8696d000-690e-11e9-9564-23077d1772c9.png)
