### ISSUE TITLE
Add and Remove responsible members in Query page gives error

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks#99]
1. open any open query, click on + button for adding new responsible member (Tanvi, Swati)
2. gives error "Object reff not set".
![2019-02-14_14-00-06](https://user-images.githubusercontent.com/46882964/52774041-64591a00-3062-11e9-9f71-3b195a313c67.jpg)

3. Remove responsible person 1st time not working, 
4. give error than
![2019-02-14_14-13-59](https://user-images.githubusercontent.com/46882964/52774478-4809ad00-3063-11e9-93b3-178016e4a5ee.jpg)

**Comment by ajayrajecb** [comment]
problem only occurs when we select tanvi, swati , nitish as members

**Comment by mitulpanch** [comment]
This wont happen in Live Database, but still keep it open, We should check this on Live once Released.
